# Step 3 — Council Services and Facilities Information

## Objective

This notebook extracts, cleans, and curates information about services
and facilities associated with Kabwe Municipal Council.

The information will be obtained from official Kabwe Municipal Council
webpages and official council documents.

The dataset will focus on:

- council services;
- public facilities and amenities;
- service descriptions;
- departments or units responsible for services;
- locations where available; and
- official sources supporting the extracted information.

Source URLs will be retained to provide data provenance.

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
council_base_url = "https://www.kabwecouncil.gov.zm"

print("Official council website:")
print(council_base_url)

Official council website:
https://www.kabwecouncil.gov.zm

In [3]:
response = requests.get(
    council_base_url,
    timeout=30,
    verify=False
)

print("Status code:", response.status_code)
print("Content type:", response.headers.get("Content-Type"))
print("Page size:", len(response.text), "characters")

C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Status code: 200
Content type: text/html; charset=UTF-8
Page size: 161404 characters

In [4]:
soup = BeautifulSoup(
    response.text,
    "html.parser"
)

homepage_text = soup.get_text(
    separator="\n",
    strip=True
)

print("First 5000 characters of the council homepage:")
print("-----------------------------------------------")
print(homepage_text[:5000])

First 5000 characters of the council homepage:
-----------------------------------------------
Kabwe Municipal Council – Kabwe
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Search
Freedom way
kabwecouncil.gov.zm
Mon - Fri 08:00 - 17:00
PAYING PROPERTY RATES  IS LAW .PAY YOUR RATES NOW FOR IMPROVED SEREVICE DELIVERY .TOGETHER WE CAN TRANSFORM KABWE
KABWE  MUNICIPAL  COUNCIL
About Local Government
Click Here
Click Here
Itaba Maize Seed Facility In Zambia
Beyer seed
POTHOLE PATCHING BUNTUNGWA ROAD
R0AD WORKS IN MUWOWO EAST
Community Projects
Click Here
FULL COUNCIL  MEETING
The Mayor
Kabwe Central
Bwacha
Know your  civic Leaders
Mr. Garry Domingo
His Worship The Mayor.
Welcome To Kabwe District
A warm welcome to Kabwe Municipal Council website, a platform created to give you, our valued and esteemed public the opportunity to interact with us, as well as to ensure that information on services and opportunities available in Kabwe District is made available and easily accessible by you the general public. Kabwe is the Provincial capital of Central Province situated along the Great North road 139Km.
Read More..
Mr.
Town Clerk.
Keep Kabwe Clean,
Green
& Healthy
Let’s build the
Zambia we want!
.
The Ministry of Local Government and Rural Developement has unveiled the Keep Zambia Clean, Green and Healthy Communication Strategy (2024-2028). Supported by a robust legal framework, the strategy aims to inspire the behavioural changes essential for effective solid waste management across communities.
Click here
Cleaning at the Railway Crossing
Click Here
Women led the change in town cleanup
Click Here
Making Kabwe Clean & Green
Click Here
Teamwork  & Community spirit of working together to make kabwe cleaner  and Greener & healthier
Click Here
Previous
Next
Attention!! application for 2026
is now closed for all
categories
Constituency Development Fund (CDF)
CDF Tracker
View resources available by Constituency.
View Tracker
CDF News:
CDF Skills Bursaries Applicants
Download Latest Statement
View Previous Statements
CDF Guidelines
View guidelines for CDF funds.
Download Guidelines
Previous
Next
Latest News
49 DISTRICT VOTER EDUCATION FACILITATORS DEPLOYED BY ECZ IN KABWE DISTRICT.
Read More »
KABWE MUNICIPAL COUNCIL ENGAGES STAKEHOLDERS ON PROPOSED NEW BY-LAWS
Kabwe Municipal Council has received widespread commendation for initiating stakeholder consultations on six proposed new by-laws aimed at protecting the environment, curbing land degradation, and
Read More »
KABWE SELECTED FOR NATIONAL FUKUOKA LANDFILL TRAINING.
KABWE SELECTED FOR NATIONAL FUKUOKA LANDFILL TRAINING 8th December 2025. We are proud to be part of the on-going Ministry of Local Government and Rural
Read More »
KABWE FIRE BRIGADE PREVENTS A HOUSE TURNING INTO ASHES.
Kabwe – 8th December 2025. KABWE MUNICIPAL COUNCIL FIRE BRIGADE PREVENTS A HOUSE TURNING INTO ASHES. Kabwe Municipal Council fire fighters this morning prevented a
Read More »
CDF PROJECT MONITORING BY KABWE MUNICIPAL COUNCIL MANAGEMENT TEAM
Yesterday, a senior management team conducted on-site inspections of the 2025-approved Constituency Development Fund (CDF) projects across Kabwe Central and Bwacha constituencies. The exercise focused
Read More »
Contact Information
Kabwe Municipal Council
Central Province, Zambia
Tel: 260 215 224 238
P.O Box: 80424
Email: kabwemunicipalcouncil@gmail.com
Complaint
Follow Us
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
SMART Zambia
©2023. SMART Zambia Institute. All Rights Reserved.

In [5]:
services_urls = {
    "licenses_and_levies": (
        council_base_url + "/?page_id=2142"
    ),
    "waste_management": (
        council_base_url + "/?page_id=2150"
    ),
    "e_gp": (
        council_base_url + "/?page_id=2155"
    )
}

print("Council Services URLs:")
print("======================")

for service, url in services_urls.items():
    print(service, ":", url)

Council Services URLs:
======================
licenses_and_levies : https://www.kabwecouncil.gov.zm/?page_id=2142
waste_management : https://www.kabwecouncil.gov.zm/?page_id=2150
e_gp : https://www.kabwecouncil.gov.zm/?page_id=2155

In [6]:
service_responses = {}

for service, url in services_urls.items():
    try:
        page_response = requests.get(
            url,
            timeout=30,
            verify=False
        )

        service_responses[service] = page_response

        print(service)
        print("URL:", url)
        print("Status code:", page_response.status_code)
        print("Content type:", page_response.headers.get("Content-Type"))
        print("Page size:", len(page_response.text), "characters")
        print("----------------------------------------")

    except requests.RequestException as error:
        print(service)
        print("Error:", error)
        print("----------------------------------------")

C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

licenses_and_levies
URL: https://www.kabwecouncil.gov.zm/?page_id=2142
Status code: 200
Content type: text/html; charset=UTF-8
Page size: 88964 characters
----------------------------------------

C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

waste_management
URL: https://www.kabwecouncil.gov.zm/?page_id=2150
Status code: 200
Content type: text/html; charset=UTF-8
Page size: 83062 characters
----------------------------------------

C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

e_gp
URL: https://www.kabwecouncil.gov.zm/?page_id=2155
Status code: 200
Content type: text/html; charset=UTF-8
Page size: 82960 characters
----------------------------------------

In [7]:
service_texts = {}

for service, page_response in service_responses.items():
    service_soup = BeautifulSoup(
        page_response.text,
        "html.parser"
    )

    service_texts[service] = service_soup.get_text(
        separator="\n",
        strip=True
    )

    print("=" * 60)
    print(service.upper())
    print("=" * 60)
    print(service_texts[service][:5000])
    print()

============================================================
LICENSES_AND_LEVIES
============================================================
IMG-20250115-WA0025 – Kabwe Municipal Council
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Search
IMG-20250115-WA0025
Published in
Home SZI
Full size
744 × 744
Contact Information
Kabwe Municipal Council
Central Province, Zambia
Tel: 260 215 224 238
P.O Box: 80424
Email: kabwemunicipalcouncil@gmail.com
Complaint
Follow Us
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
SMART Zambia
©2023. SMART Zambia Institute. All Rights Reserved.

============================================================
WASTE_MANAGEMENT
============================================================
1000810471-removebg-preview – Kabwe Municipal Council
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Search
1000810471-removebg-preview
Published in
Home SZI
Full size
500 × 500
Contact Information
Kabwe Municipal Council
Central Province, Zambia
Tel: 260 215 224 238
P.O Box: 80424
Email: kabwemunicipalcouncil@gmail.com
Complaint
Follow Us
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
SMART Zambia
©2023. SMART Zambia Institute. All Rights Reserved.

============================================================
E_GP
============================================================
1000812999-removebg-preview – Kabwe Municipal Council
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Search
1000812999-removebg-preview
Published in
Home SZI
Full size
469 × 532
Contact Information
Kabwe Municipal Council
Central Province, Zambia
Tel: 260 215 224 238
P.O Box: 80424
Email: kabwemunicipalcouncil@gmail.com
Complaint
Follow Us
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
SMART Zambia
©2023. SMART Zambia Institute. All Rights Reserved.

In [8]:
services_data = [
    [
        "Licenses and levies",
        "Council service listed under the Services section of the official website",
        "Council Service",
        "Official webpage",
        services_urls["licenses_and_levies"]
    ],
    [
        "Waste Management",
        "Council service listed under the Services section of the official website",
        "Council Service",
        "Official webpage",
        services_urls["waste_management"]
    ],
    [
        "E-GP",
        "Council service listed under the Services section of the official website",
        "Council Service",
        "Official webpage",
        services_urls["e_gp"]
    ]
]

services_df = pd.DataFrame(
    services_data,
    columns=[
        "service",
        "description",
        "category",
        "source_type",
        "source_url"
    ]
)

display(services_df)

,service,description,category,source_type,source_url
0,Licenses and levies,Council service listed under the Services sect...,Council Service,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2142
1,Waste Management,Council service listed under the Services sect...,Council Service,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2150
2,E-GP,Council service listed under the Services sect...,Council Service,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2155

In [9]:
departments_url = council_base_url + "/?page_id=2072"

departments_response = requests.get(
    departments_url,
    timeout=30,
    verify=False
)

print("Departments page:")
print("URL:", departments_url)
print("Status code:", departments_response.status_code)
print("Content type:", departments_response.headers.get("Content-Type"))
print("Page size:", len(departments_response.text), "characters")

C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Departments page:
URL: https://www.kabwecouncil.gov.zm/?page_id=2072
Status code: 404
Content type: text/html; charset=UTF-8
Page size: 87471 characters

In [10]:
department_links = []

for link in soup.find_all("a", href=True):
    link_text = link.get_text(" ", strip=True)

    if (
        "dept" in link_text.lower()
        or "office of the town clerk" in link_text.lower()
    ):
        department_links.append(
            {
                "department": link_text,
                "url": link["href"]
            }
        )

departments_df = pd.DataFrame(
    department_links
).drop_duplicates()

display(departments_df)

,department,url
0,Dept of Human Resource and Administration,https://www.kabwecouncil.gov.zm/?page_id=2637
1,Dept of Health,https://www.kabwecouncil.gov.zm/?page_id=2640
2,Dept of Finance,https://www.kabwecouncil.gov.zm/?page_id=2643
3,Dept of Engineering Services,https://www.kabwecouncil.gov.zm/?page_id=2646
4,Dept of Health Services,https://www.kabwecouncil.gov.zm/?page_id=2649
5,Dept Legal ( Services Unit),https://www.kabwecouncil.gov.zm/?page_id=3894
6,Dept Of Planning,https://www.kabwecouncil.gov.zm/?page_id=3897
7,Dept Of Housing and Social Services,https://www.kabwecouncil.gov.zm/?page_id=3900
8,"Dept of Fisheries, Livestock And Veterinary Se...",https://www.kabwecouncil.gov.zm/?page_id=3903
9,Dept of Agriculture,https://www.kabwecouncil.gov.zm/?page_id=3906

In [11]:
departments_df = departments_df.copy()

# Remove empty department names
departments_df = departments_df[
    departments_df["department"].notna()
]

# Remove empty URLs
departments_df = departments_df[
    departments_df["url"].notna()
]

# Remove duplicate department/URL combinations
departments_df = departments_df.drop_duplicates(
    subset=["department", "url"]
)

# Reset the row numbers
departments_df = departments_df.reset_index(drop=True)

print("Number of department links found:", len(departments_df))
print()

display(departments_df)

Number of department links found: 10

,department,url
0,Dept of Human Resource and Administration,https://www.kabwecouncil.gov.zm/?page_id=2637
1,Dept of Health,https://www.kabwecouncil.gov.zm/?page_id=2640
2,Dept of Finance,https://www.kabwecouncil.gov.zm/?page_id=2643
3,Dept of Engineering Services,https://www.kabwecouncil.gov.zm/?page_id=2646
4,Dept of Health Services,https://www.kabwecouncil.gov.zm/?page_id=2649
5,Dept Legal ( Services Unit),https://www.kabwecouncil.gov.zm/?page_id=3894
6,Dept Of Planning,https://www.kabwecouncil.gov.zm/?page_id=3897
7,Dept Of Housing and Social Services,https://www.kabwecouncil.gov.zm/?page_id=3900
8,"Dept of Fisheries, Livestock And Veterinary Se...",https://www.kabwecouncil.gov.zm/?page_id=3903
9,Dept of Agriculture,https://www.kabwecouncil.gov.zm/?page_id=3906

In [12]:
department_status = []

for _, row in departments_df.iterrows():
    department = row["department"]
    url = row["url"]

    try:
        department_response = requests.get(
            url,
            timeout=30,
            verify=False
        )

        department_status.append(
            [
                department,
                url,
                department_response.status_code,
                len(department_response.text)
            ]
        )

    except requests.RequestException as error:
        department_status.append(
            [
                department,
                url,
                "ERROR",
                str(error)
            ]
        )

department_status_df = pd.DataFrame(
    department_status,
    columns=[
        "department",
        "url",
        "status_code",
        "page_size"
    ]
)

display(department_status_df)

C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

,department,url,status_code,page_size
0,Dept of Human Resource and Administration,https://www.kabwecouncil.gov.zm/?page_id=2637,200,110630
1,Dept of Health,https://www.kabwecouncil.gov.zm/?page_id=2640,200,137426
2,Dept of Finance,https://www.kabwecouncil.gov.zm/?page_id=2643,200,97841
3,Dept of Engineering Services,https://www.kabwecouncil.gov.zm/?page_id=2646,200,100085
4,Dept of Health Services,https://www.kabwecouncil.gov.zm/?page_id=2649,200,117513
5,Dept Legal ( Services Unit),https://www.kabwecouncil.gov.zm/?page_id=3894,200,112308
6,Dept Of Planning,https://www.kabwecouncil.gov.zm/?page_id=3897,200,105198
7,Dept Of Housing and Social Services,https://www.kabwecouncil.gov.zm/?page_id=3900,200,100272
8,"Dept of Fisheries, Livestock And Veterinary Se...",https://www.kabwecouncil.gov.zm/?page_id=3903,200,123830
9,Dept of Agriculture,https://www.kabwecouncil.gov.zm/?page_id=3906,200,92673

In [13]:
department_texts = {}

for _, row in department_status_df.iterrows():

    department = row["department"]
    url = row["url"]

    if row["status_code"] == 200:

        department_response = requests.get(
            url,
            timeout=30,
            verify=False
        )

        department_soup = BeautifulSoup(
            department_response.text,
            "html.parser"
        )

        department_texts[department] = department_soup.get_text(
            separator="\n",
            strip=True
        )

print("Number of department pages extracted:", len(department_texts))

C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(
C:\Users\Pardo\AppData\Local\Programs\Python\Python314\Lib\site-packages\urllib3\connectionpool.py:1110: InsecureRequestWarning: Unverified HTTPS request is being made to host 'www.kabwecouncil.gov.zm'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

Number of department pages extracted: 10

In [14]:
for department, text in department_texts.items():

    print("=" * 70)
    print(department.upper())
    print("=" * 70)

    lines = [
        line.strip()
        for line in text.splitlines()
        if line.strip()
    ]

    # Remove obvious repeated navigation items
    useful_lines = []

    for line in lines:
        if line not in useful_lines:
            useful_lines.append(line)

    print("\n".join(useful_lines[:80]))
    print()

======================================================================
DEPT OF HUMAN RESOURCE AND ADMINISTRATION
======================================================================
Dept of Human Resource and Administration – Kabwe Municipal Council
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Licenses and levies
Waste Management
E-GP
News Updates
CDF
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Search
Human Resource and Administration
NSAKANYA J CHANGWE
Director of Human Resource and Administration
A small river named Duden flows by their place and supplies it with the necessary
Phone:
+1 (859) 254-6589
Email:
info@example.com
The directorate is headed by a Director who is responsible for the sections/units that fall under the department. The units that fall under the directorate are Human Resources, General Administration, Registry, Committee, and Police.
Human Resource Section
The Unit is responsible for personnel and establishment management. It provides strategies for the acquisition, utilization, improvement, and retention of an enterprise’s human resources. Other responsibilities for the unit are:
Conducting performance appraisal.
Conduct performance management.
Conduct staff audit.
Carry out orientation and induction programs.
Management and interpretation of the conditions of service.
Management of employee relations
Prevention of industrial relation
General Administration Section
This unit is responsible for the general administration and running of the day-to-day office operations. The following are some of the functions/services:
Facilitate the solemnizing of marriages
Procure of office furniture and equipment.
Promote staff health and safety in the council. Identify the number of sick people as well as visit the visit. Identify prone risk areas.
Transport Management. Manages effectively the availability of transport to facilitate staff mobility and transportation of materials and equipment.
Licensing and insuring. Facilitate the licensing and insurance of all vehicles for Mongu Municipal Council.
Office accommodation. Provide timely provision of office space for officers to create a conducive work environment.
Management of clerical services.
General maintenance of office spaces and surrounding.
Council Police Section
The unit is responsible for Community police, Maintain Security, and Law and order. Facilitate for Security measures, Law, and order in the Council.
Committee Section
The committee section plays the role of secretariate in all council meetings. Their role is to document and minute all meetings a from Management meeting, various committees and the full council meeting.
Registry Section
Responsible for records management and filling of council records and correspondences.
Contact Information
Kabwe Municipal Council
Central Province, Zambia

======================================================================
DEPT OF HEALTH
======================================================================
Dept of Health – Kabwe Municipal Council
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Licenses and levies
Waste Management
E-GP
News Updates
CDF
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Search
Derpartments
public health Department
Christopher Mtonga
Director Public Health
The Public Health Department safeguards the health of the community by preventing, controlling and eliminating diseases. Additionally it is mandated with solid waste management and the delivery of targeted health education to help people live longer and healthier lives.
Our core mandate is drawn from the
Food Safety Act No. 7 of 2019, Local Government Act No. 2 of 2019, Solid Waste Regulation and Management No. 20 of 2018, Liquor Licensing Act No. 20 of 2011, and the Public Health Act Cap 295
of the Laws of Zambia.
These pieces of legislation employ the department to deliver district-wide programmes and projects to prevent, control, and eliminate diseases, enforce Environmental Health, Port Health, Food, and Drugs policies to reduce outbreak risks. They also mandate us to inspect food outlets, workplaces, and public nuisances. To uphold health standards Run awareness campaigns and enforce the Public Health Act through community education Execute pest and vector control operations Manage cemeteries, crematoria, and burial services for safe, sanitary disposal of human remains
KEY SERVICES
Environmental Health
Disease Prevention & Control
• Community health screenings
• Vaccination drives and outbreak response
Environmental & Port Health
• Waste-management guidelines
• Ship and border health inspections
Food Safety & Workplace Inspections
• Routine audits of restaurants, markets, and factories
• Compliance certification
Public Awareness & Education
• Workshops, school programmes, and media campaigns
• IEC materials and behaviour-change initiatives
Pest & Vector Management
• Mosquito, rodent, and vector surveillance
• Spraying and community clean-up events
Funeral & Burial Services
• Cemetery administration and plot allocation
• Crematorium operations and mortuary support
Public Health Unit
Overview
Charged with disease prevention, control and health promotion through research, surveillance and community engagement.
Implements environmental, food, drugs and port health policies to mitigate hazards and protect public well-being
Determine community health status via research and surveys
Monitor disease trends and epidemiological patterns
Enforce public health guidelines and standards
Support stakeholders with technical expertise

======================================================================
DEPT OF FINANCE
======================================================================
Dept of Finance – Kabwe Municipal Council
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Licenses and levies
Waste Management
E-GP
News Updates
CDF
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Search
Derpartments
Finance Department
Jane Doe
Director Finance
The department is under the leadership of the Director of Finance, who oversees all financial operations. This includes the management of bank accounts, the preparation of financial reports, the maintenance of asset registers, the maintenance of the Valuation roll, and the supervision of stores, among other responsibilities
Establishment
The section is responsible for managing and computing all expenses related to staff establishment and personal emoluments.
Accountancy
Revenue
Contact Information
Kabwe Municipal Council
Central Province, Zambia
Tel: 260 215 224 238
P.O Box: 80424
Email: kabwemunicipalcouncil@gmail.com
Complaint
Follow Us
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
SMART Zambia
©2023. SMART Zambia Institute. All Rights Reserved.

======================================================================
DEPT OF ENGINEERING SERVICES
======================================================================
Dept of Engineering Services – Kabwe Municipal Council
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Licenses and levies
Waste Management
E-GP
News Updates
CDF
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Search
Engineering Services
Jane Doe
Director Engineering Services
A small river named Duden flows by their place and supplies it with the necessary
Phone:
+1 (859) 254-6589
Email:
info@example.com
The Directorate of Engineering Services is charged with the supervision and delivery of public works and engineering services in the district. The department also houses the Fire and Rescue Services under which the fire brigade falls.
Contact Information
Kabwe Municipal Council
Central Province, Zambia
Tel: 260 215 224 238
P.O Box: 80424
Email: kabwemunicipalcouncil@gmail.com
Complaint
Follow Us
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
SMART Zambia
©2023. SMART Zambia Institute. All Rights Reserved.

======================================================================
DEPT OF HEALTH SERVICES
======================================================================
Dept of Health Services – Kabwe Municipal Council
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Licenses and levies
Waste Management
E-GP
News Updates
CDF
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Search
Departments Health Services
Jane Doe
Designer
A small river named Duden flows by their place and supplies it with the necessary
Phone:
+1 (859) 254-6589
Email:
info@example.com
Department Of Health Services
The Department of Health Services at Kazungula Town Council is responsible for the provision of preventive and curative healthcare services through general nursing care, clinical care, provision of medical equipment, and pharmaceutical services.
Our focus is on promoting health, prolonging life, and preventing diseases across the district. The department leads programmes that address critical health issues such as maternal and child health, nutrition, communicable diseases, environmental health, and community-based healthcare outreach.
This department operates through two core sections:
Health Services
and
Public Health Services
, each supported by specialised units and professional staff who work tirelessly to ensure quality and equitable healthcare for all residents both in the peri-urban and rural centres.
RESPONSIBILITIES
Deliver general clinical care and nursing services.
Provide pharmaceutical and diagnostic services, including imaging and laboratory testing.
Implement vaccination campaigns and child health programmes.
Coordinate maternal health and family planning services.
Monitor and manage communicable and neglected tropical diseases.
Provide nutrition counselling and services.
Manage health education and disease surveillance programmes.
Ensure availability and maintenance of medical equipment in health facilities.
Manage ambulance and emergency referral services.
.
KEY SUB-UNITS AND FUNCTIONS
The Department is led by the
Director of Health Services
, supported by technical officers and specialists across several key units as outlined below:
Health Services Section
Edit
This section is responsible for coordinating the provision of preventive and curative health services through general nursing care, clinical care, medical equipment, and pharmaceutical services. The section is also responsible for District Hospitals, Mini Hospitals, Zonal Health Centres, Health Centres and Health Posts.
Units under this section include:
Clinical Care and Diagnostic Services Unit
Coordinates outpatient and inpatient care, diagnostics, pharmacy services, and biomedical support.

======================================================================
DEPT LEGAL ( SERVICES UNIT)
======================================================================
Dept Legal ( Services Unit) – Kabwe Municipal Council
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Licenses and levies
Waste Management
E-GP
News Updates
CDF
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Search
Legal Department
Lubeta Muyabala
Council Advocate
A small river named Duden flows by their place and supplies it with the necessary
Phone:
+1 (859) 254-6589
Email:
info@example.com
The Department of Legal Services is responsible for providing legal advise to the Council. Its core functions include ensuring that the local authority operates within the confines of established laws that govern the local government system.The Department further executes various functions inter alia; drafting commercial contracts, Provision of Legal opinions, processing land applications, trading licenses applications, processing of Certificates of Title and occupancy licenses issued under the Urban and Regional Planning Act No.3 of 2015 of the Laws of Zambia etc. The Directorate has four (4) Sections:
Litigation
Estates
Licensing
Contracts
The litigation section is responsible for conducting research and timely litigation of matters on behalf of the Council, both as Plaintiff or Defendant in order to safeguard and preserve its interests. This Section is further mandated to prosecute offenders as provided by the Local Government Act No.2 of 2019 of the Laws of Zambia. Furthermore, the department handles cases that are referred to the Directorate from other Councils within Western Province or any other council that may need legal services.
The  Council has the authority to deal;
a) State Land
b) Housing (Statutory and Improvements) Area
Procedure for allocation of land
Land identification
Approval of plan by Council
Advertisement placed in the newspaper for applications
All applications reported to the Plans, Works and Development Committee, and full Council Offer letters and demands.
The section processes applications for various trading licenses relevant for conducting business in Mongu district pursuant to the Trades Licensing Act, Chapter 393 of the Laws of Zambia and Liquor Licensing Act No. 20 of 2011 on behalf of the Liquor Licensing Board. The process of issuing various licenses includes filing in an application in a prescribed manner, assessment/inspection of the business premises before issuance of the respective license or trading permit.
In order to enhance compliance with laid down regulations and laws by license holders, the Licensing section together with Department of Human Resource and Administration (Council Police Unit) and Department of Public Health conduct inspection of various business ventures, and failure to comply with statutory requirement attracts a penalty and/or prosecution as prescribed by the Acts that govern the activities.
Contrats
The section is responsible for the preparation of commercial contracts, Memorandum of Understanding (MoU), and Memorandum of Agreements (MoAs) concerning and relating to the Council. Common contracts under the Section include;
Construction/Building Contracts
Contracts for Supply and Delivery of Services
Contracts for Supply of Goods
Contracts of sale
Lease agreements in respect of Council properties; and
Employment Contracts
Contact Information
Kabwe Municipal Council
Central Province, Zambia
Tel: 260 215 224 238
P.O Box: 80424

======================================================================
DEPT OF PLANNING
======================================================================
Dept Of Planning – Kabwe Municipal Council
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Licenses and levies
Waste Management
E-GP
News Updates
CDF
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Search
The Department of Planning
Chansa Mwila
Director Planning
The Planning Department holds the authority for both Rural and Urban Planning and Development control, as outlined by
The Urban and Regional Planning Act
.
Under the supervision of the Director of Planning, the department is tasked with establishing a clear developmental framework and roadmap for the district. To accomplish these developmental goals, the department operates through its seven units.
Town Planning
Building Inspections
The Town Planning Section executes town planning strategies to achieve a harmonious and acceptable urban environment. The key responsibilities under this section include:
Design of local Area plans.
Numbering of Plots
Forward Planning.
Coordination of transport routes and bus stations to optimise city planning
This section holds the responsibility for development control. The primary duties of this unit include the following tasks:
Building Inspections.
Identify illegal structures and unauthorized development.
Enforce compliance
Survey Section
Social Economic Planning
The section is responsible for guiding land boundary limits. Some of the major tasks are:
Placement and Re-Establishing of property boundaries.
Road marking.
Preparation of survey diagrams.
Preparation of survey reports.
Management of Geographical Information Systems (GIS)
The section is mandated to undertake socio-economic planning to enhance the implementation of Council developmental plans and programs. Key responsibilities include:
Development Planning.
Capacity building.
Project Proposals.
Coordinate Constituency Development Fund (CDF) activities
Monitoring and Evaluation.
Research.
Environmental Planning
he section is mandated to with the responsibility of mainstreaming environmental concerns in development plans and programs to enhance sustainability. Key responsibilities include:
Preparation of Environmental Assessment Reports.
Environmental Profiling.


## Step 3.17 — Department Page Data Quality Note

The official Kabwe Municipal Council website contains detailed information
on several departmental pages, including descriptions of services,
responsibilities, and functions.

During extraction, some departmental pages were found to contain apparent
template or copy-editing errors. For example, certain pages refer to other
local authorities such as Mongu Municipal Council or Kazungula Town Council.

Therefore, information containing an incorrect local-authority reference
will not automatically be treated as a Kabwe-specific fact.

For this dataset, service information will be included only where:

- the service or function is clearly identified on the official council
  webpage;
- the information is relevant to the department being described; and
- the information does not depend on an obviously incorrect reference to
  another local authority.

This approach preserves the provenance of the official source while
reducing the risk of introducing inaccurate information into the dataset.

In [15]:
curated_services = [
    [
        "Environmental Health",
        "Safeguards community health through environmental health activities",
        "Public Health Department",
        "Council Service"
    ],
    [
        "Disease Prevention and Control",
        "Provides disease prevention, control, health screening and outbreak response activities",
        "Public Health Department",
        "Council Service"
    ],
    [
        "Waste Management",
        "Provides solid waste management and waste-management activities",
        "Public Health Department",
        "Council Service"
    ],
    [
        "Food Safety and Workplace Inspections",
        "Inspects restaurants, markets, factories and workplaces and supports compliance certification",
        "Public Health Department",
        "Council Service"
    ],
    [
        "Public Health Awareness and Education",
        "Provides workshops, school programmes, media campaigns and community education",
        "Public Health Department",
        "Council Service"
    ],
    [
        "Pest and Vector Management",
        "Provides pest and vector surveillance, spraying and community clean-up activities",
        "Public Health Department",
        "Council Service"
    ],
    [
        "Funeral and Burial Services",
        "Provides cemetery administration, plot allocation, crematorium operations and mortuary support",
        "Public Health Department",
        "Council Service"
    ],
    [
        "Clinical and Nursing Services",
        "Provides preventive and curative healthcare through clinical and nursing services",
        "Health Services Department",
        "Council Service"
    ],
    [
        "Pharmaceutical and Diagnostic Services",
        "Provides pharmaceutical services and diagnostic services including laboratory testing",
        "Health Services Department",
        "Council Service"
    ],
    [
        "Vaccination and Child Health Programmes",
        "Implements vaccination campaigns and child health programmes",
        "Health Services Department",
        "Council Service"
    ],
    [
        "Maternal Health and Family Planning",
        "Coordinates maternal health and family planning services",
        "Health Services Department",
        "Council Service"
    ],
    [
        "Health Education and Disease Surveillance",
        "Manages health education and disease surveillance programmes",
        "Health Services Department",
        "Council Service"
    ],
    [
        "Legal Advisory Services",
        "Provides legal advice to the Council and supports compliance with applicable laws",
        "Legal Services Department",
        "Council Service"
    ],
    [
        "Trading Licence Processing",
        "Processes applications for various trading licences and permits",
        "Legal Services Department",
        "Council Service"
    ],
    [
        "Land Application Processing",
        "Processes land applications and supports land-related administrative procedures",
        "Legal Services Department",
        "Council Service"
    ],
    [
        "Building Inspections",
        "Conducts building inspections and identifies unauthorised development",
        "Planning Department",
        "Council Service"
    ],
    [
        "Plot Numbering",
        "Provides plot numbering as part of town planning activities",
        "Planning Department",
        "Council Service"
    ],
    [
        "Survey Services",
        "Provides property boundary, road marking, survey diagram and survey report services",
        "Planning Department",
        "Council Service"
    ],
    [
        "GIS Management",
        "Manages geographical information systems",
        "Planning Department",
        "Council Service"
    ],
    [
        "Environmental Planning",
        "Supports environmental assessment, environmental profiling and environmental planning",
        "Planning Department",
        "Council Service"
    ],
    [
        "Community Development Services",
        "Facilitates community development activities and community mobilisation",
        "Housing and Social Services Department",
        "Council Service"
    ],
    [
        "Social Protection Programmes",
        "Coordinates and implements social protection programmes",
        "Housing and Social Services Department",
        "Council Service"
    ],
    [
        "Housing Services",
        "Supports housing services and upgrading of unplanned settlements",
        "Housing and Social Services Department",
        "Council Service"
    ],
    [
        "Markets and Bus Stations Management",
        "Manages markets and bus stations to support smooth operations and revenue collection",
        "Housing and Social Services Department",
        "Council Service"
    ],
    [
        "Library Services",
        "Provides library services",
        "Housing and Social Services Department",
        "Council Service"
    ],
    [
        "Sports and Recreation",
        "Provides sports and recreation activities",
        "Housing and Social Services Department",
        "Council Service"
    ],
    [
        "Skills Development",
        "Supports skills development programmes within communities",
        "Housing and Social Services Department",
        "Council Service"
    ],
    [
        "Veterinary Services",
        "Provides veterinary services across the district",
        "Fisheries, Livestock and Veterinary Services Department",
        "Council Service"
    ],
    [
        "Livestock Development",
        "Supports livestock productivity, welfare and sustainable livestock farming",
        "Fisheries, Livestock and Veterinary Services Department",
        "Council Service"
    ],
    [
        "Fisheries and Aquaculture Services",
        "Supports fisheries and aquaculture development, training, regulation and education",
        "Fisheries, Livestock and Veterinary Services Department",
        "Council Service"
    ],
    [
        "Agricultural Extension Services",
        "Provides extension services to farmers and supports agricultural development",
        "Agriculture Department",
        "Council Service"
    ]
]

curated_services_df = pd.DataFrame(
    curated_services,
    columns=[
        "service",
        "description",
        "department",
        "category"
    ]
)

display(curated_services_df)

,service,description,department,category
0,Environmental Health,Safeguards community health through environmen...,Public Health Department,Council Service
1,Disease Prevention and Control,"Provides disease prevention, control, health s...",Public Health Department,Council Service
2,Waste Management,Provides solid waste management and waste-mana...,Public Health Department,Council Service
3,Food Safety and Workplace Inspections,"Inspects restaurants, markets, factories and w...",Public Health Department,Council Service
4,Public Health Awareness and Education,"Provides workshops, school programmes, media c...",Public Health Department,Council Service
5,Pest and Vector Management,"Provides pest and vector surveillance, sprayin...",Public Health Department,Council Service
6,Funeral and Burial Services,"Provides cemetery administration, plot allocat...",Public Health Department,Council Service
7,Clinical and Nursing Services,Provides preventive and curative healthcare th...,Health Services Department,Council Service
8,Pharmaceutical and Diagnostic Services,Provides pharmaceutical services and diagnosti...,Health Services Department,Council Service
9,Vaccination and Child Health Programmes,Implements vaccination campaigns and child hea...,Health Services Department,Council Service
10,Maternal Health and Family Planning,Coordinates maternal health and family plannin...,Health Services Department,Council Service
11,Health Education and Disease Surveillance,Manages health education and disease surveilla...,Health Services Department,Council Service
12,Legal Advisory Services,Provides legal advice to the Council and suppo...,Legal Services Department,Council Service
13,Trading Licence Processing,Processes applications for various trading lic...,Legal Services Department,Council Service
14,Land Application Processing,Processes land applications and supports land-...,Legal Services Department,Council Service
15,Building Inspections,Conducts building inspections and identifies u...,Planning Department,Council Service
16,Plot Numbering,Provides plot numbering as part of town planni...,Planning Department,Council Service
17,Survey Services,"Provides property boundary, road marking, surv...",Planning Department,Council Service
18,GIS Management,Manages geographical information systems,Planning Department,Council Service
19,Environmental Planning,"Supports environmental assessment, environment...",Planning Department,Council Service
20,Community Development Services,Facilitates community development activities a...,Housing and Social Services Department,Council Service
21,Social Protection Programmes,Coordinates and implements social protection p...,Housing and Social Services Department,Council Service
22,Housing Services,Supports housing services and upgrading of unp...,Housing and Social Services Department,Council Service
23,Markets and Bus Stations Management,Manages markets and bus stations to support sm...,Housing and Social Services Department,Council Service
24,Library Services,Provides library services,Housing and Social Services Department,Council Service
25,Sports and Recreation,Provides sports and recreation activities,Housing and Social Services Department,Council Service
26,Skills Development,Supports skills development programmes within ...,Housing and Social Services Department,Council Service
27,Veterinary Services,Provides veterinary services across the district,"Fisheries, Livestock and Veterinary Services D...",Council Service
28,Livestock Development,"Supports livestock productivity, welfare and s...","Fisheries, Livestock and Veterinary Services D...",Council Service
29,Fisheries and Aquaculture Services,Supports fisheries and aquaculture development...,"Fisheries, Livestock and Veterinary Services D...",Council Service
30,Agricultural Extension Services,Provides extension services to farmers and sup...,Agriculture Department,Council Service

In [16]:
# Create a lookup table connecting each department
# to its official Kabwe Municipal Council webpage.

department_url_lookup = dict(
    zip(
        departments_df["department"],
        departments_df["url"]
    )
)

# Add the official source URL to each service record.
curated_services_df["source_type"] = "Official council webpage"

curated_services_df["source_url"] = (
    curated_services_df["department"]
    .map(department_url_lookup)
)

display(curated_services_df)

,service,description,department,category,source_type,source_url
0,Environmental Health,Safeguards community health through environmen...,Public Health Department,Council Service,Official council webpage,NaN
1,Disease Prevention and Control,"Provides disease prevention, control, health s...",Public Health Department,Council Service,Official council webpage,NaN
2,Waste Management,Provides solid waste management and waste-mana...,Public Health Department,Council Service,Official council webpage,NaN
3,Food Safety and Workplace Inspections,"Inspects restaurants, markets, factories and w...",Public Health Department,Council Service,Official council webpage,NaN
4,Public Health Awareness and Education,"Provides workshops, school programmes, media c...",Public Health Department,Council Service,Official council webpage,NaN
5,Pest and Vector Management,"Provides pest and vector surveillance, sprayin...",Public Health Department,Council Service,Official council webpage,NaN
6,Funeral and Burial Services,"Provides cemetery administration, plot allocat...",Public Health Department,Council Service,Official council webpage,NaN
7,Clinical and Nursing Services,Provides preventive and curative healthcare th...,Health Services Department,Council Service,Official council webpage,NaN
8,Pharmaceutical and Diagnostic Services,Provides pharmaceutical services and diagnosti...,Health Services Department,Council Service,Official council webpage,NaN
9,Vaccination and Child Health Programmes,Implements vaccination campaigns and child hea...,Health Services Department,Council Service,Official council webpage,NaN
10,Maternal Health and Family Planning,Coordinates maternal health and family plannin...,Health Services Department,Council Service,Official council webpage,NaN
11,Health Education and Disease Surveillance,Manages health education and disease surveilla...,Health Services Department,Council Service,Official council webpage,NaN
12,Legal Advisory Services,Provides legal advice to the Council and suppo...,Legal Services Department,Council Service,Official council webpage,NaN
13,Trading Licence Processing,Processes applications for various trading lic...,Legal Services Department,Council Service,Official council webpage,NaN
14,Land Application Processing,Processes land applications and supports land-...,Legal Services Department,Council Service,Official council webpage,NaN
15,Building Inspections,Conducts building inspections and identifies u...,Planning Department,Council Service,Official council webpage,NaN
16,Plot Numbering,Provides plot numbering as part of town planni...,Planning Department,Council Service,Official council webpage,NaN
17,Survey Services,"Provides property boundary, road marking, surv...",Planning Department,Council Service,Official council webpage,NaN
18,GIS Management,Manages geographical information systems,Planning Department,Council Service,Official council webpage,NaN
19,Environmental Planning,"Supports environmental assessment, environment...",Planning Department,Council Service,Official council webpage,NaN
20,Community Development Services,Facilitates community development activities a...,Housing and Social Services Department,Council Service,Official council webpage,NaN
21,Social Protection Programmes,Coordinates and implements social protection p...,Housing and Social Services Department,Council Service,Official council webpage,NaN
22,Housing Services,Supports housing services and upgrading of unp...,Housing and Social Services Department,Council Service,Official council webpage,NaN
23,Markets and Bus Stations Management,Manages markets and bus stations to support sm...,Housing and Social Services Department,Council Service,Official council webpage,NaN
24,Library Services,Provides library services,Housing and Social Services Department,Council Service,Official council webpage,NaN
25,Sports and Recreation,Provides sports and recreation activities,Housing and Social Services Department,Council Service,Official council webpage,NaN
26,Skills Development,Supports skills development programmes within ...,Housing and Social Services Department,Council Service,Official council webpage,NaN
27,Veterinary Services,Provides veterinary services across the district,"Fisheries, Livestock and Veterinary Services D...",Council Service,Official council webpage,NaN
28,Livestock Development,"Supports livestock productivity, welfare and s...","Fisheries, Livestock and Veterinary Services D...",Council Service,Official council webpage,NaN
29,Fisheries and Aquaculture Services,Supports fisheries and aquaculture development...,"Fisheries, Livestock and Veterinary Services D...",Council Service,Official council webpage,NaN
30,Agricultural Extension Services,Provides extension services to farmers and sup...,Agriculture Department,Council Service,Official council webpage,NaN

In [17]:
# Manually map each department used in the curated dataset
# to the correct official Kabwe Municipal Council webpage.

department_url_map = {
    "Public Health Department": department_links[
        next(
            i for i, item in enumerate(department_links)
            if "health" in item["department"].lower()
            and "health services" not in item["department"].lower()
        )
    ]["url"],

    "Health Services Department": department_links[
        next(
            i for i, item in enumerate(department_links)
            if "health services" in item["department"].lower()
        )
    ]["url"],

    "Legal Services Department": department_links[
        next(
            i for i, item in enumerate(department_links)
            if "legal" in item["department"].lower()
        )
    ]["url"],

    "Planning Department": department_links[
        next(
            i for i, item in enumerate(department_links)
            if "planning" in item["department"].lower()
        )
    ]["url"],

    "Housing and Social Services Department": department_links[
        next(
            i for i, item in enumerate(department_links)
            if "housing" in item["department"].lower()
        )
    ]["url"],

    "Fisheries, Livestock and Veterinary Services Department": department_links[
        next(
            i for i, item in enumerate(department_links)
            if "fisheries" in item["department"].lower()
        )
    ]["url"],

    "Agriculture Department": department_links[
        next(
            i for i, item in enumerate(department_links)
            if "agriculture" in item["department"].lower()
        )
    ]["url"]
}

# Add source information
curated_services_df["source_type"] = "Official council webpage"

curated_services_df["source_url"] = (
    curated_services_df["department"]
    .map(department_url_map)
)

display(curated_services_df)

,service,description,department,category,source_type,source_url
0,Environmental Health,Safeguards community health through environmen...,Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
1,Disease Prevention and Control,"Provides disease prevention, control, health s...",Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
2,Waste Management,Provides solid waste management and waste-mana...,Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
3,Food Safety and Workplace Inspections,"Inspects restaurants, markets, factories and w...",Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
4,Public Health Awareness and Education,"Provides workshops, school programmes, media c...",Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
5,Pest and Vector Management,"Provides pest and vector surveillance, sprayin...",Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
6,Funeral and Burial Services,"Provides cemetery administration, plot allocat...",Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
7,Clinical and Nursing Services,Provides preventive and curative healthcare th...,Health Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2649
8,Pharmaceutical and Diagnostic Services,Provides pharmaceutical services and diagnosti...,Health Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2649
9,Vaccination and Child Health Programmes,Implements vaccination campaigns and child hea...,Health Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2649
10,Maternal Health and Family Planning,Coordinates maternal health and family plannin...,Health Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2649
11,Health Education and Disease Surveillance,Manages health education and disease surveilla...,Health Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2649
12,Legal Advisory Services,Provides legal advice to the Council and suppo...,Legal Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3894
13,Trading Licence Processing,Processes applications for various trading lic...,Legal Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3894
14,Land Application Processing,Processes land applications and supports land-...,Legal Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3894
15,Building Inspections,Conducts building inspections and identifies u...,Planning Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3897
16,Plot Numbering,Provides plot numbering as part of town planni...,Planning Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3897
17,Survey Services,"Provides property boundary, road marking, surv...",Planning Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3897
18,GIS Management,Manages geographical information systems,Planning Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3897
19,Environmental Planning,"Supports environmental assessment, environment...",Planning Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3897
20,Community Development Services,Facilitates community development activities a...,Housing and Social Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3900
21,Social Protection Programmes,Coordinates and implements social protection p...,Housing and Social Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3900
22,Housing Services,Supports housing services and upgrading of unp...,Housing and Social Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3900
23,Markets and Bus Stations Management,Manages markets and bus stations to support sm...,Housing and Social Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3900
24,Library Services,Provides library services,Housing and Social Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3900
25,Sports and Recreation,Provides sports and recreation activities,Housing and Social Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3900
26,Skills Development,Supports skills development programmes within ...,Housing and Social Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3900
27,Veterinary Services,Provides veterinary services across the district,"Fisheries, Livestock and Veterinary Services D...",Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3903
28,Livestock Development,"Supports livestock productivity, welfare and s...","Fisheries, Livestock and Veterinary Services D...",Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3903
29,Fisheries and Aquaculture Services,Supports fisheries and aquaculture development...,"Fisheries, Livestock and Veterinary Services D...",Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3903
30,Agricultural Extension Services,Provides extension services to farmers and sup...,Agriculture Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3906

In [18]:
# Check whether any source URLs are missing

missing_urls = curated_services_df[
    curated_services_df["source_url"].isna()
]

print("Number of services:", len(curated_services_df))
print("Missing source URLs:", len(missing_urls))

if len(missing_urls) > 0:
    print("\nServices with missing URLs:")
    display(
        missing_urls[
            ["service", "department"]
        ]
    )
else:
    print("All services have official source URLs.")

Number of services: 31
Missing source URLs: 0
All services have official source URLs.

In [19]:
# Prepare the three services listed directly under
# the official Council Services section.

standalone_services_df = services_df.copy()

# Rename the columns so they match the curated services dataset.
standalone_services_df = standalone_services_df[
    [
        "service",
        "description",
        "category",
        "source_type",
        "source_url"
    ]
]

# Add a department column.
standalone_services_df["department"] = "Council Services"

# Reorder columns to match the departmental dataset.
standalone_services_df = standalone_services_df[
    [
        "service",
        "description",
        "department",
        "category",
        "source_type",
        "source_url"
    ]
]

display(standalone_services_df)

,service,description,department,category,source_type,source_url
0,Licenses and levies,Council service listed under the Services sect...,Council Services,Council Service,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2142
1,Waste Management,Council service listed under the Services sect...,Council Services,Council Service,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2150
2,E-GP,Council service listed under the Services sect...,Council Services,Council Service,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2155

In [20]:
# Select the columns from the departmental services
# so that they match the standalone services dataset.

departmental_services_df = curated_services_df[
    [
        "service",
        "description",
        "department",
        "category",
        "source_type",
        "source_url"
    ]
].copy()

# Combine departmental services with the services
# listed directly under the Council Services section.

all_services_df = pd.concat(
    [
        departmental_services_df,
        standalone_services_df
    ],
    ignore_index=True
)

print("Total services collected:", len(all_services_df))

display(all_services_df)

Total services collected: 34

,service,description,department,category,source_type,source_url
0,Environmental Health,Safeguards community health through environmen...,Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
1,Disease Prevention and Control,"Provides disease prevention, control, health s...",Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
2,Waste Management,Provides solid waste management and waste-mana...,Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
3,Food Safety and Workplace Inspections,"Inspects restaurants, markets, factories and w...",Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
4,Public Health Awareness and Education,"Provides workshops, school programmes, media c...",Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
5,Pest and Vector Management,"Provides pest and vector surveillance, sprayin...",Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
6,Funeral and Burial Services,"Provides cemetery administration, plot allocat...",Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
7,Clinical and Nursing Services,Provides preventive and curative healthcare th...,Health Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2649
8,Pharmaceutical and Diagnostic Services,Provides pharmaceutical services and diagnosti...,Health Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2649
9,Vaccination and Child Health Programmes,Implements vaccination campaigns and child hea...,Health Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2649
10,Maternal Health and Family Planning,Coordinates maternal health and family plannin...,Health Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2649
11,Health Education and Disease Surveillance,Manages health education and disease surveilla...,Health Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2649
12,Legal Advisory Services,Provides legal advice to the Council and suppo...,Legal Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3894
13,Trading Licence Processing,Processes applications for various trading lic...,Legal Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3894
14,Land Application Processing,Processes land applications and supports land-...,Legal Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3894
15,Building Inspections,Conducts building inspections and identifies u...,Planning Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3897
16,Plot Numbering,Provides plot numbering as part of town planni...,Planning Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3897
17,Survey Services,"Provides property boundary, road marking, surv...",Planning Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3897
18,GIS Management,Manages geographical information systems,Planning Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3897
19,Environmental Planning,"Supports environmental assessment, environment...",Planning Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3897
20,Community Development Services,Facilitates community development activities a...,Housing and Social Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3900
21,Social Protection Programmes,Coordinates and implements social protection p...,Housing and Social Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3900
22,Housing Services,Supports housing services and upgrading of unp...,Housing and Social Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3900
23,Markets and Bus Stations Management,Manages markets and bus stations to support sm...,Housing and Social Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3900
24,Library Services,Provides library services,Housing and Social Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3900
25,Sports and Recreation,Provides sports and recreation activities,Housing and Social Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3900
26,Skills Development,Supports skills development programmes within ...,Housing and Social Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3900
27,Veterinary Services,Provides veterinary services across the district,"Fisheries, Livestock and Veterinary Services D...",Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3903
28,Livestock Development,"Supports livestock productivity, welfare and s...","Fisheries, Livestock and Veterinary Services D...",Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3903
29,Fisheries and Aquaculture Services,Supports fisheries and aquaculture development...,"Fisheries, Livestock and Veterinary Services D...",Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3903
30,Agricultural Extension Services,Provides extension services to farmers and sup...,Agriculture Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=3906
31,Licenses and levies,Council service listed under the Services sect...,Council Services,Council Service,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2142
32,Waste Management,Council service listed under the Services sect...,Council Services,Council Service,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2150
33,E-GP,Council service listed under the Services sect...,Council Services,Council Service,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2155

In [21]:
# Check the combined services dataset for missing values.

print("Missing values by column:")
print("--------------------------------")

print(
    all_services_df.isnull().sum()
)

print("\nTotal duplicate rows:")
print("--------------------------------")

print(
    all_services_df.duplicated().sum()
)

print("\nDuplicate service names:")
print("--------------------------------")

duplicate_services = all_services_df[
    all_services_df["service"].duplicated(
        keep=False
    )
].sort_values("service")

if len(duplicate_services) > 0:
    display(duplicate_services)
else:
    print("No duplicate service names found.")

Missing values by column:
--------------------------------
service        0
description    0
department     0
category       0
source_type    0
source_url     0
dtype: int64

Total duplicate rows:
--------------------------------
0

Duplicate service names:
--------------------------------

,service,description,department,category,source_type,source_url
2,Waste Management,Provides solid waste management and waste-mana...,Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
32,Waste Management,Council service listed under the Services sect...,Council Services,Council Service,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2150

In [22]:
# Add a unique identifier to each service record.

all_services_df.insert(
    0,
    "service_id",
    range(1, len(all_services_df) + 1)
)

print("Number of service records:", len(all_services_df))
print("Number of columns:", len(all_services_df.columns))

display(all_services_df.head(10))

Number of service records: 34
Number of columns: 7

,service_id,service,description,department,category,source_type,source_url
0,1,Environmental Health,Safeguards community health through environmen...,Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
1,2,Disease Prevention and Control,"Provides disease prevention, control, health s...",Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
2,3,Waste Management,Provides solid waste management and waste-mana...,Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
3,4,Food Safety and Workplace Inspections,"Inspects restaurants, markets, factories and w...",Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
4,5,Public Health Awareness and Education,"Provides workshops, school programmes, media c...",Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
5,6,Pest and Vector Management,"Provides pest and vector surveillance, sprayin...",Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
6,7,Funeral and Burial Services,"Provides cemetery administration, plot allocat...",Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
7,8,Clinical and Nursing Services,Provides preventive and curative healthcare th...,Health Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2649
8,9,Pharmaceutical and Diagnostic Services,Provides pharmaceutical services and diagnosti...,Health Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2649
9,10,Vaccination and Child Health Programmes,Implements vaccination campaigns and child hea...,Health Services Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2649

In [23]:
# Final quality checks for the Council Services and Facilities dataset.

print("FINAL DATASET QUALITY CHECK")
print("=" * 50)

print("Number of records:", len(all_services_df))
print("Number of columns:", len(all_services_df.columns))

print("\nMissing values:")
print(all_services_df.isnull().sum())

print("\nDuplicate rows:")
print(all_services_df.duplicated().sum())

print("\nDuplicate service IDs:")
print(all_services_df["service_id"].duplicated().sum())

print("\nUnique departments:")
print(all_services_df["department"].nunique())

print("\nUnique services:")
print(all_services_df["service"].nunique())

print("\nSource types:")
print(all_services_df["source_type"].value_counts())

print("\nDataset columns:")
print(list(all_services_df.columns))

FINAL DATASET QUALITY CHECK
==================================================
Number of records: 34
Number of columns: 7

Missing values:
service_id     0
service        0
description    0
department     0
category       0
source_type    0
source_url     0
dtype: int64

Duplicate rows:
0

Duplicate service IDs:
0

Unique departments:
8

Unique services:
33

Source types:
source_type
Official council webpage    31
Official webpage             3
Name: count, dtype: int64

Dataset columns:
['service_id', 'service', 'description', 'department', 'category', 'source_type', 'source_url']

In [24]:
# Standardize source_type values so that the dataset
# uses one consistent description for official webpages.

all_services_df["source_type"] = (
    all_services_df["source_type"]
    .replace(
        {
            "Official webpage": "Official council webpage"
        }
    )
)

print("Standardized source types:")
print(
    all_services_df["source_type"].value_counts()
)

display(
    all_services_df[
        [
            "service_id",
            "service",
            "source_type"
        ]
    ].head(10)
)

Standardized source types:
source_type
Official council webpage    34
Name: count, dtype: int64

,service_id,service,source_type
0,1,Environmental Health,Official council webpage
1,2,Disease Prevention and Control,Official council webpage
2,3,Waste Management,Official council webpage
3,4,Food Safety and Workplace Inspections,Official council webpage
4,5,Public Health Awareness and Education,Official council webpage
5,6,Pest and Vector Management,Official council webpage
6,7,Funeral and Burial Services,Official council webpage
7,8,Clinical and Nursing Services,Official council webpage
8,9,Pharmaceutical and Diagnostic Services,Official council webpage
9,10,Vaccination and Child Health Programmes,Official council webpage

In [25]:
# Export the cleaned Council Services and Facilities dataset
# using the required pipe delimiter.

services_output_file = (
    "db-unza26-csc4792-council-services-and-facilities.csv"
)

all_services_df.to_csv(
    services_output_file,
    sep="|",
    index=False,
    encoding="utf-8"
)

print("Dataset exported successfully.")
print("File:", services_output_file)
print("Records:", len(all_services_df))
print("Columns:", len(all_services_df.columns))

Dataset exported successfully.
File: db-unza26-csc4792-council-services-and-facilities.csv
Records: 34
Columns: 7

In [26]:
# Reload the exported CSV to verify that it was saved
# correctly and can be read back into pandas.

verification_df = pd.read_csv(
    services_output_file,
    sep="|",
    encoding="utf-8"
)

print("CSV verification")
print("=" * 40)

print("Records loaded:", len(verification_df))
print("Columns loaded:", len(verification_df.columns))

print("\nColumns:")
print(list(verification_df.columns))

print("\nMissing values:")
print(verification_df.isnull().sum())

print("\nFirst 5 records:")
display(verification_df.head())

CSV verification
========================================
Records loaded: 34
Columns loaded: 7

Columns:
['service_id', 'service', 'description', 'department', 'category', 'source_type', 'source_url']

Missing values:
service_id     0
service        0
description    0
department     0
category       0
source_type    0
source_url     0
dtype: int64

First 5 records:

,service_id,service,description,department,category,source_type,source_url
0,1,Environmental Health,Safeguards community health through environmen...,Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
1,2,Disease Prevention and Control,"Provides disease prevention, control, health s...",Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
2,3,Waste Management,Provides solid waste management and waste-mana...,Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
3,4,Food Safety and Workplace Inspections,"Inspects restaurants, markets, factories and w...",Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
4,5,Public Health Awareness and Education,"Provides workshops, school programmes, media c...",Public Health Department,Council Service,Official council webpage,https://www.kabwecouncil.gov.zm/?page_id=2640

In [27]:
# Create a source register for the Council Services and Facilities dataset.

step3_sources = [
    [
        "Council homepage",
        "Official council website and navigation used to identify services and departments",
        council_base_url
    ],
    [
        "Licenses and levies",
        "Official Council Services webpage",
        services_urls["licenses_and_levies"]
    ],
    [
        "Waste Management",
        "Official Council Services webpage",
        services_urls["waste_management"]
    ],
    [
        "E-GP",
        "Official Council Services webpage",
        services_urls["e_gp"]
    ]
]

# Add the department webpages used in the curated service dataset.
for department, url in department_url_map.items():
    step3_sources.append(
        [
            department,
            "Official departmental webpage",
            url
        ]
    )

step3_sources_df = pd.DataFrame(
    step3_sources,
    columns=[
        "source_name",
        "description",
        "source_url"
    ]
)

# Remove any accidental duplicate URLs.
step3_sources_df = (
    step3_sources_df
    .drop_duplicates(subset=["source_url"])
    .reset_index(drop=True)
)

print("Number of Step 3 sources:", len(step3_sources_df))

display(step3_sources_df)

Number of Step 3 sources: 11

,source_name,description,source_url
0,Council homepage,Official council website and navigation used t...,https://www.kabwecouncil.gov.zm
1,Licenses and levies,Official Council Services webpage,https://www.kabwecouncil.gov.zm/?page_id=2142
2,Waste Management,Official Council Services webpage,https://www.kabwecouncil.gov.zm/?page_id=2150
3,E-GP,Official Council Services webpage,https://www.kabwecouncil.gov.zm/?page_id=2155
4,Public Health Department,Official departmental webpage,https://www.kabwecouncil.gov.zm/?page_id=2640
5,Health Services Department,Official departmental webpage,https://www.kabwecouncil.gov.zm/?page_id=2649
6,Legal Services Department,Official departmental webpage,https://www.kabwecouncil.gov.zm/?page_id=3894
7,Planning Department,Official departmental webpage,https://www.kabwecouncil.gov.zm/?page_id=3897
8,Housing and Social Services Department,Official departmental webpage,https://www.kabwecouncil.gov.zm/?page_id=3900
9,"Fisheries, Livestock and Veterinary Services D...",Official departmental webpage,https://www.kabwecouncil.gov.zm/?page_id=3903
10,Agriculture Department,Official departmental webpage,https://www.kabwecouncil.gov.zm/?page_id=3906

In [28]:
# Validate the Step 3 source register.

print("STEP 3 SOURCE REGISTER VALIDATION")
print("=" * 50)

print("Number of sources:", len(step3_sources_df))

print("\nMissing values:")
print(step3_sources_df.isnull().sum())

print("\nDuplicate source URLs:")
print(
    step3_sources_df["source_url"].duplicated().sum()
)

print("\nSource types:")
print(
    step3_sources_df["description"].value_counts()
)

STEP 3 SOURCE REGISTER VALIDATION
==================================================
Number of sources: 11

Missing values:
source_name    0
description    0
source_url     0
dtype: int64

Duplicate source URLs:
0

Source types:
description
Official departmental webpage                                                        7
Official Council Services webpage                                                    3
Official council website and navigation used to identify services and departments    1
Name: count, dtype: int64

In [29]:
# Export the Step 3 source register.

sources_output_file = (
    "db-unza26-csc4792-csc4792-council-services-sources.csv"
)

step3_sources_df.to_csv(
    sources_output_file,
    sep="|",
    index=False,
    encoding="utf-8"
)

print("Source register exported successfully.")
print("File:", sources_output_file)
print("Sources:", len(step3_sources_df))

Source register exported successfully.
File: db-unza26-csc4792-csc4792-council-services-sources.csv
Sources: 11

In [30]:
sources_output_file = (
    "db-unza26-csc4792-council-services-sources.csv"
)

step3_sources_df.to_csv(
    sources_output_file,
    sep="|",
    index=False,
    encoding="utf-8"
)

print("Source register exported successfully.")
print("File:", sources_output_file)
print("Sources:", len(step3_sources_df))

Source register exported successfully.
File: db-unza26-csc4792-council-services-sources.csv
Sources: 11

## Step 3 — Council Services and Facilities: Summary

The Council Services and Facilities dataset was created from official
Kabwe Municipal Council webpages.

The extraction identified:

- 34 service records;
- 33 unique service names;
- 8 departments/categories represented;
- 11 official source webpages;
- 0 missing values;
- 0 duplicate records; and
- 0 duplicate source URLs.

The dataset was exported using the pipe (`|`) delimiter.

### Output Files

1. `db-unza26-csc4792-council-services-and-facilities.csv`
2. `db-unza26-csc4792-council-services-sources.csv`

The dataset retains source URLs for provenance and includes services
identified from both the Council's Services section and departmental
webpages.

Where departmental webpages contained apparent references to other local
authorities, those locality-specific statements were excluded from the
curated service records rather than being treated as Kabwe-specific facts.