# Step 2 — Ward Development Committee Information

## 2.1 Objective

This section extracts and curates information about Ward Development
Committees (WDCs) associated with Kabwe Municipal Council.

The official Kabwe Municipal Council website is used as the primary source.

The extraction will focus on:

- the meaning and purpose of Ward Development Committees;
- the number of WDCs in Kabwe;
- the number of wards covered by WDCs;
- constituency distribution of the wards;
- WDC-related functions and activities;
- official documents and webpages providing WDC information.

Information will be extracted from official webpages and official PDF
documents where applicable.

Source URLs will be retained to provide data provenance.

In [19]:
# Official sources for Ward Development Committee information.

wdc_sources = {
    "faq": "https://www.kabwecouncil.gov.zm/?page_id=2173",
    
    "stakeholder_plan_2025": (
        "https://www.kabwecouncil.gov.zm/wp-content/uploads/"
        "2025/12/2025-Stakeholders-Engagement-Plan.pdf"
    ),
    
    "budget_2025": (
        "https://www.kabwecouncil.gov.zm/wp-content/uploads/"
        "2025/05/2025-KABWE-M-COUNCIL-OBB.pdf"
    )
}

wdc_sources

{'faq': 'https://www.kabwecouncil.gov.zm/?page_id=2173',
 'stakeholder_plan_2025': 'https://www.kabwecouncil.gov.zm/wp-content/uploads/2025/12/2025-Stakeholders-Engagement-Plan.pdf',
 'budget_2025': 'https://www.kabwecouncil.gov.zm/wp-content/uploads/2025/05/2025-KABWE-M-COUNCIL-OBB.pdf'}

In [20]:
import urllib3
import requests
from bs4 import BeautifulSoup
urllib3.disable_warnings()

faq_url = wdc_sources["faq"]

faq_response = requests.get(
    faq_url,
    timeout=30,
    verify=False
)

print("Status code:", faq_response.status_code)
print("Content type:", faq_response.headers.get("Content-Type"))

Status code: 200
Content type: text/html; charset=UTF-8

In [21]:
faq_soup = BeautifulSoup(
    faq_response.text,
    "html.parser"
)

print(faq_soup.title.get_text(strip=True))

FAQS – Kabwe Municipal Council

In [22]:
faq_text = faq_soup.get_text(
    separator="\n",
    strip=True
)

print(faq_text[:5000])

FAQS – Kabwe Municipal Council
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Search
Frequently Asked Questions
What is CDF?
CDF is short for Constituency Development Fund. Through an Act of Parliament, the Government of Zambia was introduced into the CDF Act. The Constituency Development Fund was first established in Zambia in 1995 to fund micro-community development projects. The Act that guides the management and implementation of CDF has undergone several amendments over the years, the new and expanded scope of the CDF now looks at various others among others; Secondary School Boarding Bursaries, Youth and Women Empowerment grants, Loans and Community Projects.
What are WDCs?
WDC is short for Ward Development Committee. These committees are the grass root link between the communities and the Local Authorities, they are formed in each ward through an electoral process in which residents of each particular ward select representatives among themselves to pick community leaders who will represent them in the handling of the affairs of community development.
How can i be part of WDC?
The WDC is a nonpartisan committee with the sole purpose of steering the developmental agenda at the grassroots and closer to the community. Members are elected into office through an elective process overseen by the Local Authority.
Contact Information
Kabwe Municipal Council
Central Province, Zambia
Tel: 260 215 224 238
P.O Box: 80424
Email: kabwemunicipalcouncil@gmail.com
Complaint
Follow Us
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
SMART Zambia
©2023. SMART Zambia Institute. All Rights Reserved.

In [23]:
import pandas as pd
wdc_general_info = [
    [
        "WDC abbreviation",
        "WDC",
        "Ward Development Committee",
        "FAQ",
        faq_url
    ],
    [
        "WDC role",
        "Grassroots link between communities and local authorities",
        "Ward Development Committee",
        "FAQ",
        faq_url
    ],
    [
        "WDC purpose",
        "Steering the developmental agenda at grassroots level and closer to the community",
        "Ward Development Committee",
        "FAQ",
        faq_url
    ],
    [
        "Membership selection",
        "Members are elected through an electoral process overseen by the Local Authority",
        "Ward Development Committee",
        "FAQ",
        faq_url
    ]
]

wdc_general_df = pd.DataFrame(
    wdc_general_info,
    columns=[
        "field",
        "value",
        "category",
        "source_type",
        "source_url"
    ]
)

display(wdc_general_df)

,field,value,category,source_type,source_url
0,WDC abbreviation,WDC,Ward Development Committee,FAQ,https://www.kabwecouncil.gov.zm/?page_id=2173
1,WDC role,Grassroots link between communities and local ...,Ward Development Committee,FAQ,https://www.kabwecouncil.gov.zm/?page_id=2173
2,WDC purpose,Steering the developmental agenda at grassroot...,Ward Development Committee,FAQ,https://www.kabwecouncil.gov.zm/?page_id=2173
3,Membership selection,Members are elected through an electoral proce...,Ward Development Committee,FAQ,https://www.kabwecouncil.gov.zm/?page_id=2173

In [24]:
import urllib3
urllib3.disable_warnings()

stakeholder_url = wdc_sources["stakeholder_plan_2025"]

stakeholder_response = requests.get(
    stakeholder_url,
    timeout=60,
    verify=False
)

print("Status code:", stakeholder_response.status_code)
print("Content type:", stakeholder_response.headers.get("Content-Type"))
print("File size:", len(stakeholder_response.content), "bytes")

Status code: 200
Content type: application/pdf
File size: 13824643 bytes

In [25]:
import pdfplumber

print("pdfplumber is available.")

pdfplumber is available.

In [26]:
pdf_file = "2025-Stakeholders-Engagement-Plan.pdf"

with open(pdf_file, "wb") as file:
    file.write(stakeholder_response.content)

print("PDF saved:", pdf_file)

PDF saved: 2025-Stakeholders-Engagement-Plan.pdf

In [27]:
with pdfplumber.open(pdf_file) as pdf:
    print("Number of pages:", len(pdf.pages))
    
    pdf_text = ""
    
    for page_number, page in enumerate(pdf.pages, start=1):
        page_text = page.extract_text()
        
        if page_text:
            pdf_text += f"\n--- Page {page_number} ---\n"
            pdf_text += page_text

print(pdf_text[:10000])

Number of pages: 25

In [28]:
import re

# Normalize the PDF text by replacing line breaks and repeated spaces
normalized_pdf_text = re.sub(
    r"\s+",
    " ",
    pdf_text
).strip()

# Search for the important WDC information separately
search_terms = [
    "Ward Development Committees",
    "twenty-nine",
    "29",
    "Kabwe Central Constituency",
    "fourteen",
    "Bwacha Constituency",
    "fifteen"
]

print("Checking for important WDC information:")
print()

for term in search_terms:
    if term.lower() in normalized_pdf_text.lower():
        print("FOUND:", term)
    else:
        print("NOT FOUND:", term)

Checking for important WDC information:

NOT FOUND: Ward Development Committees
NOT FOUND: twenty-nine
NOT FOUND: 29
NOT FOUND: Kabwe Central Constituency
NOT FOUND: fourteen
NOT FOUND: Bwacha Constituency
NOT FOUND: fifteen

In [29]:
import os
import pdfplumber

# Check that the PDF file exists
print("PDF file:", pdf_file)
print("File exists:", os.path.exists(pdf_file))

# Check the file size
if os.path.exists(pdf_file):
    print("File size:", os.path.getsize(pdf_file), "bytes")

# Open the PDF and inspect its pages
with pdfplumber.open(pdf_file) as pdf:
    print("Number of pages:", len(pdf.pages))

    for page_number, page in enumerate(pdf.pages[:5], start=1):
        text = page.extract_text()

        print()
        print("====================================")
        print("Page", page_number)
        print("====================================")

        if text:
            print("Extracted text characters:", len(text))
            print(text[:1000])
        else:
            print("NO TEXT EXTRACTED FROM THIS PAGE")

PDF file: 2025-Stakeholders-Engagement-Plan.pdf
File exists: True
File size: 13824643 bytes
Number of pages: 25

====================================
Page 1
====================================
NO TEXT EXTRACTED FROM THIS PAGE

====================================
Page 2
====================================
NO TEXT EXTRACTED FROM THIS PAGE

====================================
Page 3
====================================
NO TEXT EXTRACTED FROM THIS PAGE

====================================
Page 4
====================================
NO TEXT EXTRACTED FROM THIS PAGE

====================================
Page 5
====================================
NO TEXT EXTRACTED FROM THIS PAGE

In [30]:
print("PDF:", pdf_file)
print("Pages:", len(pdf.pages))

print()
print("The PDF downloaded successfully.")
print("Now open the PDF file manually and search for:")
print()
print("1. 29")
print("2. twenty-nine")
print("3. Ward Development Committees")
print("4. Kabwe Central Constituency")
print("5. Bwacha Constituency")

PDF: 2025-Stakeholders-Engagement-Plan.pdf
Pages: 25

The PDF downloaded successfully.
Now open the PDF file manually and search for:

1. 29
2. twenty-nine
3. Ward Development Committees
4. Kabwe Central Constituency
5. Bwacha Constituency

In [31]:

import urllib3
import requests
from bs4 import BeautifulSoup
urllib3.disable_warnings()

search_url = "https://www.kabwecouncil.gov.zm/"

response = requests.get(
    search_url,
    timeout=30,
    verify=False
)

print("Status code:", response.status_code)
print("Content type:", response.headers.get("Content-Type"))

soup = BeautifulSoup(response.text, "html.parser")

page_text = soup.get_text(
    separator="\n",
    strip=True
)

print()
print("Searching the official website homepage...")
print()

for term in [
    "29",
    "twenty-nine",
    "Ward Development Committee",
    "ward",
    "constituency"
]:
    if term.lower() in page_text.lower():
        print("FOUND:", term)
    else:
        print("NOT FOUND:", term)

Status code: 200
Content type: text/html; charset=UTF-8

Searching the official website homepage...

NOT FOUND: 29
NOT FOUND: twenty-nine
NOT FOUND: Ward Development Committee
NOT FOUND: ward
FOUND: constituency

In [33]:
import requests
from bs4 import BeautifulSoup
import urllib3

# Suppress the warning caused by certificate verification being disabled
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

faq_url = "https://www.kabwecouncil.gov.zm/?page_id=2173"

faq_response = requests.get(
    faq_url,
    timeout=30,
    verify=False
)

print("Status code:", faq_response.status_code)
print("Content type:", faq_response.headers.get("Content-Type"))

faq_soup = BeautifulSoup(
    faq_response.text,
    "html.parser"
)

faq_text = faq_soup.get_text(
    separator="\n",
    strip=True
)

print()
print("First 5000 characters of the FAQ page:")
print("----------------------------------------")
print(faq_text[:5000])

Status code: 200
Content type: text/html; charset=UTF-8

First 5000 characters of the FAQ page:
----------------------------------------
FAQS – Kabwe Municipal Council
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Search
Frequently Asked Questions
What is CDF?
CDF is short for Constituency Development Fund. Through an Act of Parliament, the Government of Zambia was introduced into the CDF Act. The Constituency Development Fund was first established in Zambia in 1995 to fund micro-community development projects. The Act that guides the management and implementation of CDF has undergone several amendments over the years, the new and expanded scope of the CDF now looks at various others among others; Secondary School Boarding Bursaries, Youth and Women Empowerment grants, Loans and Community Projects.
What are WDCs?
WDC is short for Ward Development Committee. These committees are the grass root link between the communities and the Local Authorities, they are formed in each ward through an electoral process in which residents of each particular ward select representatives among themselves to pick community leaders who will represent them in the handling of the affairs of community development.
How can i be part of WDC?
The WDC is a nonpartisan committee with the sole purpose of steering the developmental agenda at the grassroots and closer to the community. Members are elected into office through an elective process overseen by the Local Authority.
Contact Information
Kabwe Municipal Council
Central Province, Zambia
Tel: 260 215 224 238
P.O Box: 80424
Email: kabwemunicipalcouncil@gmail.com
Complaint
Follow Us
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
SMART Zambia
©2023. SMART Zambia Institute. All Rights Reserved.

In [34]:
# Extract the WDC section from the FAQ text

wdc_start = faq_text.find("What are WDCs?")
wdc_end = faq_text.find("Contact Information")

if wdc_start != -1 and wdc_end != -1:
    wdc_section = faq_text[wdc_start:wdc_end].strip()
    
    print("Extracted WDC information:")
    print("--------------------------------")
    print(wdc_section)
else:
    print("WDC section could not be located.")

Extracted WDC information:
--------------------------------
What are WDCs?
WDC is short for Ward Development Committee. These committees are the grass root link between the communities and the Local Authorities, they are formed in each ward through an electoral process in which residents of each particular ward select representatives among themselves to pick community leaders who will represent them in the handling of the affairs of community development.
How can i be part of WDC?
The WDC is a nonpartisan committee with the sole purpose of steering the developmental agenda at the grassroots and closer to the community. Members are elected into office through an elective process overseen by the Local Authority.

In [35]:
wdc_general_info = [
    [
        "WDC abbreviation",
        "WDC",
        "Ward Development Committee",
        "Official webpage",
        faq_url
    ],
    [
        "WDC meaning",
        "Ward Development Committee",
        "Ward Development Committee",
        "Official webpage",
        faq_url
    ],
    [
        "WDC role",
        "Grassroots link between communities and Local Authorities",
        "Ward Development Committee",
        "Official webpage",
        faq_url
    ],
    [
        "WDC coverage",
        "Formed in each ward",
        "Ward Development Committee",
        "Official webpage",
        faq_url
    ],
    [
        "WDC membership selection",
        "Residents select representatives through an electoral process",
        "Ward Development Committee",
        "Official webpage",
        faq_url
    ],
    [
        "WDC nature",
        "Nonpartisan committee",
        "Ward Development Committee",
        "Official webpage",
        faq_url
    ],
    [
        "WDC purpose",
        "Steering the developmental agenda at the grassroots and closer to the community",
        "Ward Development Committee",
        "Official webpage",
        faq_url
    ],
    [
        "WDC election oversight",
        "Elective process overseen by the Local Authority",
        "Ward Development Committee",
        "Official webpage",
        faq_url
    ]
]

wdc_general_df = pd.DataFrame(
    wdc_general_info,
    columns=[
        "field",
        "value",
        "category",
        "source_type",
        "source_url"
    ]
)

display(wdc_general_df)

,field,value,category,source_type,source_url
0,WDC abbreviation,WDC,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
1,WDC meaning,Ward Development Committee,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
2,WDC role,Grassroots link between communities and Local ...,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
3,WDC coverage,Formed in each ward,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
4,WDC membership selection,Residents select representatives through an el...,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
5,WDC nature,Nonpartisan committee,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
6,WDC purpose,Steering the developmental agenda at the grass...,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
7,WDC election oversight,Elective process overseen by the Local Authority,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173

In [36]:
import requests
from bs4 import BeautifulSoup

# Search the Kabwe Municipal Council website using its WordPress search
search_url = "https://www.kabwecouncil.gov.zm/"

search_response = requests.get(
    search_url,
    timeout=30,
    verify=False
)

print("Status code:", search_response.status_code)

search_soup = BeautifulSoup(
    search_response.text,
    "html.parser"
)

# Find links containing WDC-related terms
wdc_links = []

for link in search_soup.find_all("a", href=True):
    link_text = link.get_text(" ", strip=True)
    href = link["href"]

    combined_text = f"{link_text} {href}".lower()

    if (
        "ward" in combined_text
        or "wdc" in combined_text
        or "stakeholder" in combined_text
    ):
        wdc_links.append(
            [link_text, href]
        )

print()
print("WDC-related links found on the homepage:")
print("------------------------------------------")

for item in wdc_links[:30]:
    print(item[0], "->", item[1])

Status code: 200

WDC-related links found on the homepage:
------------------------------------------
KABWE MUNICIPAL COUNCIL ENGAGES STAKEHOLDERS ON PROPOSED NEW BY-LAWS -> https://www.kabwecouncil.gov.zm/?p=4873

In [38]:
article_url = "https://www.kabwecouncil.gov.zm/?p=4873"

article_response = requests.get(
    article_url,
    timeout=30,
    verify=False
)

print("Status code:", article_response.status_code)
print("Content type:", article_response.headers.get("Content-Type"))

article_soup = BeautifulSoup(
    article_response.text,
    "html.parser"
)

article_text = article_soup.get_text(
    separator="\n",
    strip=True
)

print()
print("First 7000 characters of the article:")
print("--------------------------------------")
print(article_text[:7000])

Status code: 200
Content type: text/html; charset=UTF-8

First 7000 characters of the article:
--------------------------------------
KABWE MUNICIPAL COUNCIL ENGAGES STAKEHOLDERS ON PROPOSED NEW BY-LAWS – Kabwe Municipal Council
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Search
KABWE MUNICIPAL COUNCIL ENGAGES STAKEHOLDERS ON PROPOSED NEW BY-LAWS
Kabwe Municipal Council has received widespread commendation for initiating stakeholder consultations on six proposed new by-laws aimed at protecting the environment, curbing land degradation, and generating sustainable revenue for climate change mitigation and environmental management.
The proposed by-laws are:
-Aggregate Levy (to regulate uncontrolled sand, laterite and gravel quarrying)
-Clay Brick-Making Levy (to control unregulated brick production)
-Climate Change By-Law
-Environmental Impact Assessment By-Law
-Land and Environmental Degradation Control By-Law
-Truck Parking Levy (targeting heavy vehicle parking management)
During the consultative meeting held on Tuesday in the Council Chamber at the Civic Centre, stakeholders overwhelmingly welcomed the initiative, describing it as a timely step towards upgrading Kabwe’s long-stagnant municipal status.
Makululu Ward Development Committee Chairperson, Mr Thomson Halwembe, urged the Council to develop a strong resource mobilisation and financial strategy to ensure sufficient funds are available for town upgrading.
Luangwa Catchment Manager at Kabwe Water Resources Management Authority, Mr Anthony Chabala, and Evangelical Fellowship of Zambia Central Province Coordinator, Reverend Moses Kazimwalupya, also praised the Council’s proactive approach.
Rev. Kazimwalupya, however, stressed the importance of introducing stringent punitive measures to effectively address environmental degradation and local pollution, which he said currently pose serious risks to human health.
Other stakeholders who expressed strong support included Njanji WDC Chairperson Ms Agness Mboma, Lwasanse Ward Chairperson Mr Macmillan Chilangisha, and Ubuntungwa Youth Organisation Director Mr Mwape Mwangilwa, among others.
Earlier, Director of Legal Services at Kabwe Municipal Council, Ms Lubeta Muyabala, explained that wide stakeholder consultation is a legal requirement before any new by-laws can be enacted.
Published
December 8, 2025
By
joseph kangwa
Categorized as
Uncategorized
Post navigation
Previous post
KABWE SELECTED FOR NATIONAL FUKUOKA LANDFILL TRAINING.
Next post
49 DISTRICT VOTER EDUCATION FACILITATORS DEPLOYED BY ECZ IN KABWE DISTRICT.
Contact Information
Kabwe Municipal Council
Central Province, Zambia
Tel: 260 215 224 238
P.O Box: 80424
Email: kabwemunicipalcouncil@gmail.com
Complaint
Follow Us
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
SMART Zambia
©2023. SMART Zambia Institute. All Rights Reserved.

In [39]:
# Extract the sentences containing named WDC representatives

wdc_representative_lines = []

for line in article_text.splitlines():
    line_lower = line.lower()

    if (
        "ward development committee chairperson" in line_lower
        or "wdc chairperson" in line_lower
        or "ward chairperson" in line_lower
    ):
        wdc_representative_lines.append(line.strip())

print("WDC representative information found:")
print("---------------------------------------")

for line in wdc_representative_lines:
    print(line)

WDC representative information found:
---------------------------------------
Makululu Ward Development Committee Chairperson, Mr Thomson Halwembe, urged the Council to develop a strong resource mobilisation and financial strategy to ensure sufficient funds are available for town upgrading.
Other stakeholders who expressed strong support included Njanji WDC Chairperson Ms Agness Mboma, Lwasanse Ward Chairperson Mr Macmillan Chilangisha, and Ubuntungwa Youth Organisation Director Mr Mwape Mwangilwa, among others.

In [40]:
wdc_representatives = [
    [
        "Makululu",
        "WDC Chairperson",
        "Thomson Halwembe",
        "Official webpage",
        article_url
    ],
    [
        "Njanji",
        "WDC Chairperson",
        "Agness Mboma",
        "Official webpage",
        article_url
    ],
    [
        "Lwasanse",
        "Ward Chairperson",
        "Macmillan Chilangisha",
        "Official webpage",
        article_url
    ]
]

wdc_representatives_df = pd.DataFrame(
    wdc_representatives,
    columns=[
        "ward",
        "position",
        "person",
        "source_type",
        "source_url"
    ]
)

display(wdc_representatives_df)

,ward,position,person,source_type,source_url
0,Makululu,WDC Chairperson,Thomson Halwembe,Official webpage,https://www.kabwecouncil.gov.zm/?p=4873
1,Njanji,WDC Chairperson,Agness Mboma,Official webpage,https://www.kabwecouncil.gov.zm/?p=4873
2,Lwasanse,Ward Chairperson,Macmillan Chilangisha,Official webpage,https://www.kabwecouncil.gov.zm/?p=4873

In [41]:
budget_url = (
    "https://www.kabwecouncil.gov.zm/wp-content/uploads/"
    "2025/05/2025-KABWE-M-COUNCIL-OBB.pdf"
)

budget_response = requests.get(
    budget_url,
    timeout=60,
    verify=False
)

print("Status code:", budget_response.status_code)
print("Content type:", budget_response.headers.get("Content-Type"))
print("File size:", len(budget_response.content), "bytes")

Status code: 200
Content type: application/pdf
File size: 792438 bytes

In [42]:
import pdfplumber

budget_pdf_file = "2025-KABWE-M-COUNCIL-OBB.pdf"

with open(budget_pdf_file, "wb") as file:
    file.write(budget_response.content)

print("PDF saved:", budget_pdf_file)

with pdfplumber.open(budget_pdf_file) as pdf:
    print("Number of pages:", len(pdf.pages))

    for page_number, page in enumerate(pdf.pages[:5], start=1):
        text = page.extract_text()

        print()
        print("====================================")
        print("Page", page_number)
        print("====================================")

        if text:
            print("Extracted text characters:", len(text))
            print(text[:1000])
        else:
            print("NO TEXT EXTRACTED FROM THIS PAGE")

PDF saved: 2025-KABWE-M-COUNCIL-OBB.pdf
Number of pages: 54

====================================
Page 1
====================================
Extracted text characters: 2835
OUTPUT BASED ANNUAL BUDGET Page 1
HEA 920 KABWE MUNICIPAL COUNCIL
D 5
1.0 MANDATE
To provide operational and service excellence, innovation, community engagement and observance of
good financial management and accountability. This is in agreement with the Republican Constitution
(Amendment) Act No.2 of 2016 Part IX on the System of Devolved Governance [Article 147 (2)] and Part
XI on the System of Local Government.
2.0 STRATEGY
Kabwe Municipal Council will focus on delivering value and quality of life through good governance and
team work, involving all stakeholders including community representatives through operationalisation
of the Ward Development Committees. Further, in response to the high urbanisation rate, the Local
Authority opened up new areas for development in 2024
3.0 NATIONAL DEVELOPMENT PLAN FRAMEWORK
Cluster : 01 Economic Transformation and Job Creation
Cluster Outcome 01 An Industrialised and Diversified Economy
Strategy : 01 Improve agricultural production and product

====================================
Page 2
====================================
Extracted text characters: 480
Page 2 OUTPUT BASED ANNUAL BUDGET
HEA 920 KABWE MUNICIPAL COUNCIL
D 5
APPROVED
CODE REVENUE DESCRIPTION REVISED BUDGET
BUDGET 2025
BUDGET 2026 ESTIMATE 2027
01 Local taxes/rates
001 Residential 4,453,818 4,453,818 4,453,818
002 Commercial 5,536,418 5,536,418 5,536,418
003 Industrial 2,635,280 2,635,280 2,635,280
004 Hospitality 572,837 630,121 693,133
SubItem Total 13,198,353 13,255,637 13,318,649
001 Personal levy 450,000 495,000 220,000
SubItem Total 450,000 495,000 220,000

====================================
Page 3
====================================
Extracted text characters: 2122
OUTPUT BASED ANNUAL BUDGET Page 3
HEA 920 KABWE MUNICIPAL COUNCIL
D 5
APPROVED
CODE REVENUE DESCRIPTION REVISED BUDGET
BUDGET 2025
BUDGET 2026 ESTIMATE 2027
02 Fees and Charges
001 Consent fees 25,000 27,500 30,250
002 Survey fees 700,000 770,000 862,400
003 Building inspection-fees 250,000 300,000 300,000
004 Plan scrutiny fee 2,508,000 2,508,000 2,508,000
005 Change of premise use 295,000 324,500 347,864
006 Container/Ntemba fees 50,000 75,000 75,000
007 Rentals/lease of Council’s properties 896,400 986,040 1,084,644
008 Non-Land Application forms fees 600,000 660,000 726,000
009 Rentals from houses 85,092 93,601 102,961
011 Search fees 7,500 8,250 9,075
012 Notice board advert fees 2,500 2,750 3,025
013 Market fees 785,664 864,230 950,653
014 Parking fees 50,000 50,000 50,000
016 Loading fees (buses, trucks, trains, taxies etc.) 393,360 432,696 475,966
017 Affidavit fees 6,000 6,600 7,260
020 Hire of halls 114,684 126,152 139,824
021 Hire of grounds/stadia 13,000 60,000 75,000
024 R

====================================
Page 4
====================================
Extracted text characters: 2098
Page 4 OUTPUT BASED ANNUAL BUDGET
HEA 920 KABWE MUNICIPAL COUNCIL
D 5
APPROVED
CODE REVENUE DESCRIPTION REVISED BUDGET
BUDGET 2025
BUDGET 2026 ESTIMATE 2027
03 Licenses
002 Liquor licence 366,000 402,600 442,860
003 Firearm and ammunition licence 26,000 26,600 27,260
004 Petroleum Storage licence 400,000 440,000 492,800
005 Dog licence 40,000 44,000 49,280
SubItem Total 832,000 913,200 1,012,200
APPROVED
CODE REVENUE DESCRIPTION REVISED BUDGET
BUDGET 2025 BUDGET 2026 ESTIMATE 2027
04 Levies
001 Livestock Movement levy 32,400 32,400 32,400
002 Birds levy 60,000 66,000 72,600
004 Pole levy 40,000 44,000 49,280
006 Sand levy 43,000 47,300 52,976
011 Telecommunication Mast 220,500 220,500 220,500
017 Trading (Wholesale) Business Levy 100,000 110,000 121,000
018 Trading (Retail) Consumable groceries business 880,100 968,110 1,064,921
021 Manufacturing 62,500 68,750 75,625
029 Professional Occupation 249,900 274,890 302,379
030 Scrap Metal Dealers 12,500 13,750 15,125
031 Car Wash 20,000 22,

====================================
Page 5
====================================
Extracted text characters: 2082
OUTPUT BASED ANNUAL BUDGET Page 5
HEA 920 KABWE MUNICIPAL COUNCIL
D 5
APPROVED
CODE REVENUE DESCRIPTION REVISED BUDGET
BUDGET 2025
BUDGET 2026 ESTIMATE 2027
07 Other Incomes
099 Other Income 2,898,877 1,500,000 1,500,000
SubItem Total 2,898,877 1,500,000 1,500,000
APPROVED
CODE REVENUE DESCRIPTION REVISED BUDGET
BUDGET 2025
BUDGET 2026 ESTIMATE 2027
08 National Support (Grants)
001 Constituency Development Fund 72,116,301 72,116,301 72,116,301
002 Roads Grant 3,200,587 3,200,587 3,200,587
003 Health Grant 3,649,035 3,649,035 3,649,035
004 Local Government Equalisation Fund 23,857,381 23,857,381 23,857,381
005 Grants in lieu of Rates 1,200,000 1,200,000 1,200,000
099 Other Grants 29,494,551 10,527,645 10,797,645
SubItem Total 133,517,855 114,550,949 114,820,949
Grand Total 181,079,550 163,176,946 166,429,315
4.0 BUDGET SUMMARY
Kabwe Municipal Council's estimates of revenue and expenditure for the year 2025 stands at
approximately K181.1 million, representing a percentage increase of 28.

In [43]:
# Extract text from all pages of the 2025 budget

budget_text = ""

with pdfplumber.open(budget_pdf_file) as pdf:
    for page_number, page in enumerate(pdf.pages, start=1):
        page_text = page.extract_text()

        if page_text:
            budget_text += f"\n--- Page {page_number} ---\n"
            budget_text += page_text

print("Total extracted characters:", len(budget_text))

# Find lines containing WDC-related terms
wdc_lines = []

for line in budget_text.splitlines():
    line_lower = line.lower()

    if (
        "ward development committee" in line_lower
        or "wdc" in line_lower
    ):
        wdc_lines.append(line.strip())

print()
print("WDC-related lines found:")
print("-------------------------")

for line in wdc_lines:
    print(line)

Total extracted characters: 102784

WDC-related lines found:
-------------------------
of the Ward Development Committees. Further, in response to the high urbanisation rate, the Local
meetings and operationalisation of Ward Development Committees. The remaining K22,500 has been
Ward Development Committees (WDC's)
01 Number of Ward Development Committees (WDC's) 29 29 29 29 29
02 number of quarterly WDC meetings held 4 3 4 4 4
03 Number of WDCs oriented 29 29 29 29 29
supporting the operations of all the twenty-nine (29) Ward Development Committees in the district as well
Committee Meetings. Further, the Council has targeted to hold four (4) quarterly WDC meetings, and four
02Ward Development Committees (WDC's)
1 Number of Ward Development Committees (WDC's) 29 29 29
2 number of quarterly WDC meetings held 4 4 4
3 Number of WDCs oriented 29 29 29

In [44]:
wdc_statistics = [
    [
        "Number of Ward Development Committees",
        29,
        "Ward Development Committee statistics",
        "Official PDF",
        budget_url
    ],
    [
        "Number of WDCs oriented",
        29,
        "Ward Development Committee statistics",
        "Official PDF",
        budget_url
    ],
    [
        "Number of quarterly WDC meetings planned",
        4,
        "Ward Development Committee statistics",
        "Official PDF",
        budget_url
    ]
]

wdc_statistics_df = pd.DataFrame(
    wdc_statistics,
    columns=[
        "field",
        "value",
        "category",
        "source_type",
        "source_url"
    ]
)

display(wdc_statistics_df)

,field,value,category,source_type,source_url
0,Number of Ward Development Committees,29,Ward Development Committee statistics,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
1,Number of WDCs oriented,29,Ward Development Committee statistics,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
2,Number of quarterly WDC meetings planned,4,Ward Development Committee statistics,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...

## Step 2.25 — Obtain the Official WDC Guidelines

The official Ward Development Committee Guidelines will be used to identify
the functions and responsibilities of Ward Development Committees.

These functions will be extracted from an official Kabwe Municipal Council
document and added to the dataset with their source information.

In [45]:
wdc_guidelines_url = (
    "https://www.kabwecouncil.gov.zm/wp-content/uploads/"
    "2023/12/GUIDELINES-ON-THE-ESTABLISHMENT-OF-WARD-DEVELOPMENT-COMMITTEES.pdf"
)

guidelines_response = requests.get(
    wdc_guidelines_url,
    timeout=60,
    verify=False
)

print("Status code:", guidelines_response.status_code)
print("Content type:", guidelines_response.headers.get("Content-Type"))
print("File size:", len(guidelines_response.content), "bytes")

Status code: 200
Content type: application/pdf
File size: 1043895 bytes

In [46]:
wdc_guidelines_file = "GUIDELINES-ON-THE-ESTABLISHMENT-OF-WARD-DEVELOPMENT-COMMITTEES.pdf"

with open(wdc_guidelines_file, "wb") as file:
    file.write(guidelines_response.content)

print("PDF saved:", wdc_guidelines_file)

with pdfplumber.open(wdc_guidelines_file) as pdf:
    print("Number of pages:", len(pdf.pages))

    for page_number, page in enumerate(pdf.pages[:5], start=1):
        text = page.extract_text()

        print()
        print("====================================")
        print("Page", page_number)
        print("====================================")

        if text:
            print("Extracted text characters:", len(text))
            print(text[:1000])
        else:
            print("NO TEXT EXTRACTED FROM THIS PAGE")

PDF saved: GUIDELINES-ON-THE-ESTABLISHMENT-OF-WARD-DEVELOPMENT-COMMITTEES.pdf
Number of pages: 37

====================================
Page 1
====================================
Extracted text characters: 163
REPUBLIC OF ZAMBIA
MINISTRY OF LOCAL GOVERNMENT AND RURAL DEVELOPMENT
GUIDELINES ON THE ESTABLISHMENT,
MANAGEMENT AND OPERATION OF WARD
DEVELOPMENT COMMITTEES
2021

====================================
Page 2
====================================
Extracted text characters: 1512
FOREWORD
The Government of the Republic of Zambia is committed to actualising a devolved system of
governance as prescribed in the Constitution (Amendment) Act No. 2 of 2016. Article 147 of the
Constitution provides that the management and administration of the political, social, legal and
economic affairs of the State shall be devolved from the National Government level to the Local
Government level. Further, Article 148 establishes that local governance shall be undertaken
through sub-structures as platforms for citizen participation in decision making and development
process at the local level. In affirming the provisions of the Constitution, Part V of the Local
Government Act No. 2 of 2019, provides for the establishment of Ward Development
Committees.
The Guidelines on the Establishment, Management and Operations of Ward Development
Committees (WDCs), therefore, provide a significant demonstration of Government’s assurance
towards the implementation of Constitutional provisions on

====================================
Page 3
====================================
Extracted text characters: 665
ACRONYMS
AIDS Acquired Immuno-Deficiency Syndrome
CBO Community Based Organisation
CDF Constituency Development Fund
CSO Civil Society Organisation
DDCC District Development Coordinating Committee
DP Director of Planning
DPO District Planning Officer
DPU District Planning Unit
FBO Faith Based Organisation
HIV Human Immuno-Deficiency Virus
MLGRD Ministry of Local Government and Rural Development
MP Member of Parliament
NDP National Decentralisation Policy
NGO Non-Governmental Organisation
NRC National Registration Card
PD Polling District
WDCs Ward Development Committees
WDEC Ward Development Executive Committee
WDS-C Ward Development Sub-Committee
Page | II

====================================
Page 4
====================================
Extracted text characters: 2095
WORKING DEFINITIONS
In these Guidelines, unless the context otherwise requires:-
Accreditation Means authority or certification granted by the Local Authority to an
individual/organisation to observe or monitor Polling Station or
Totalling Centre.
By- election Means an election that is held when a vacancy occurs in the office of a
Zonal Representative.
Candidate A person contesting for the ward development committee membership.
Candidate Nomination A formal process of validating a candidate to contest a zonal election
Chairperson A person in charge of a meeting.
Committee Includes the WDC, WDEC and Sub-Committee.
Council Refers to City Council, Municipal Council, or Town Council.
Co-ordinator A person who organizes the different parts of an activity and the people
involved in it so that it works well.
District An administrative Unit of a Province.
Dissolution Refers to an act or process of disbanding the Committee.
Election A formal process of choosing by voting a person or a group of

====================================
Page 5
====================================
Extracted text characters: 1505
Polling Station A gazetted venue in a polling district where voters cast their ballot
during an election.
Register of voters The Register of Voters prepared and certified by relevant Authorities.
Presiding Officer An officer appointed by the Principal Officer to be in charge of
conducting elections.
Sub-structure Includes a district, ward and village.
Sub-National level An administrative division of Government at Provincial or District
level.
Trustee A Government officer residing within the Ward appointed by the
Council for purposes of being a caretaker of a WDC and its assets in
the event of a WDC dissolution.
Uniformed Staff Security personnel appointed to maintain law and order in and around a
nomination centre, polling station and/or totalling/collation centre.
Voter A person who is registered as a voter and whose name appears in the
Voter Register.
Ward A unit into which a district is divided for purposes of electing
councillors.
Ward Councillor Means an elected member of the Coun

In [47]:
guidelines_text = ""

with pdfplumber.open(wdc_guidelines_file) as pdf:
    for page_number, page in enumerate(pdf.pages, start=1):
        page_text = page.extract_text()

        if page_text:
            guidelines_text += f"\n--- Page {page_number} ---\n"
            guidelines_text += page_text

print("Total extracted characters:", len(guidelines_text))

wdc_guideline_lines = []

for line in guidelines_text.splitlines():
    line_lower = line.lower()

    if (
        "function" in line_lower
        or "functions" in line_lower
        or "responsibilit" in line_lower
        or "ward development committee" in line_lower
    ):
        wdc_guideline_lines.append(line.strip())

print()
print("WDC-related lines found:")
print("-------------------------")

for line in wdc_guideline_lines:
    print(line)

Total extracted characters: 52820

WDC-related lines found:
-------------------------
provide linkages among the Ward Development Committee, the Local Authorities and other
WDCs Ward Development Committees
Candidate A person contesting for the ward development committee membership.
for time being discharging the functions of their Office.
PART II: ESTABLISHMENT, COMPOSITION AND FUNCTIONS OF THE COMMITTEES .............. 2
1.2 Aims of the Ward Development Committees
FUNCTIONS OF COMMITTEES
2.1 THE WARD DEVELOPMENT COMMITTEE
this responsibility, a team of facilitators may be appointed from departments in the local
A Ward Development Committee may invite a person to attend and participate in the
2.1.3 Functions of the Ward Development Committee
The functions of a Ward Development Committee are to:
xiv. Manage and keep a record of resources allocated to the Ward Development Committee;
xvii. Execute other functions as delegated by the Local Authority excluding delegated Central
Government functions to Local Authorities.
2.1.4 Functions of the Councillor and Ex-officios
Tabulated below are the specific roles and responsibilities of the Councillor, Ex-officios, and
S/No. Position Roles/Responsibilities
2.2.3 Functions of the WDEC
Tabulated below are the specific roles and responsibilities of the members of the WDEC.
S/No Position Roles/Responsibilities
x. Perform any other roles or responsibilities incidental or connected
x. Perform any other roles or responsibilities incidental or connected
vii. Perform any other roles or responsibilities incidental or connected
iii. Perform all functions in good faith without fear or favour; and
iv. Perform any other roles or responsibilities incidental or connected
2.3.3 Functions of Sub-Committees
The functions of the Finance and Planning Sub-Committee shall be to-
xvii. Perform any other function as delegated by the WDC.
The functions of the infrastructure development Sub-Committee shall be to -
vii. Perform any other function as delegated by the WDC.
The functions of the Socio-Economic Sub-Committee shall be to -
vi. Perform any other function as delegated by the WDC.
i. A member of the Ward Development Committee shall hold office for a term of two and a
iii. The election of a Ward Development Committee shall be held within two months after
The office of a member of a Ward Development Committee shall be vacant if a member:
ii. Is legally disqualified from discharging the functions of office;
Where a vacancy occurs in the office of an elected Ward Development Committee member, a
The tenure of a Ward Development Committee shall lapse on the dissolution of the National
Assembly. A Local Authority may dissolve a Ward Development Committee on:
ii. Non-performance of the WDEC according to their roles and responsibilities;
functions. The cardinal tenets of discipline shall be morality, ethics, human-dignity, equity,
6.1.3 Independent Appeals Committee of Ward Development Committees
7.2 Bank Account of Ward Development Committee
ii. The WDC shall not assume the roles and responsibilities of other institutions operating in
...................................Ward Development Committee
WARD DEVELOPMENT COMMITTEE – ZONAL REPRESENTATIVE ELECTIONS
The following outlines the Ward Development Committee Code of Conduct:
to be exemplary during the discharge of their duties and functions.
Members shall not attend meetings and/or other official functions, under the
Members shall not allocate land as such a responsibility remains the preserve of

In [48]:
functions_start = guidelines_text.find(
    "2.1.3 Functions of the Ward Development Committee"
)

functions_end = guidelines_text.find(
    "2.1.4 Functions of the Councillor and Ex-officios"
)

if functions_start != -1 and functions_end != -1:
    wdc_functions_section = guidelines_text[
        functions_start:functions_end
    ].strip()

    print("WDC Functions Section:")
    print("======================")
    print(wdc_functions_section)
else:
    print("The WDC functions section could not be located.")

WDC Functions Section:
======================
2.1.3 Functions of the Ward Development Committee
The functions of a Ward Development Committee are to:
i. Prepare annual Ward Development Plans;
ii. Collect revenue, levies and fees on behalf of a Local Authority on appointment by
resolution of the Council;
iii. Monitor and evaluate Ward development projects;
iv. Promote community engagement in Ward development Planning;
v. Formulate and submit a project list and budget proposals to the Constituency
Development Fund (CDF) Committee in the first quarter of every year preceding the year
in which a project is proposed to be implemented;
vi. Support research on an area of study for the advancement of the local community;
vii. Facilitate the identification of potential areas of investment and promote sustainable local
economic development;
viii. Promote and participate in the co-management of natural and trans-boundary resources
between or among wards;
ix. Provide a forum for dialogue and coordination on Ward development issues;
x. Identify areas for capacity building within the ward;
xi. Promote and encourage village regrouping and urban renewal activities;
xii. Identify in the ward, and submit to the Local Authority, potential areas of revenue
sources likely to broaden the revenue base of the Local Authority;
xiii. Prudently manage resources allocated to the ward by the Local Authority in line with
principles of public financial management;
xiv. Manage and keep a record of resources allocated to the Ward Development Committee;
xv. Prepare quarterly reports on developmental activities within the ward to the appropriate
committee of the Local Authority;
xvi. Develop and maintain a ward based database as guided by the Local Authority; and
xvii. Execute other functions as delegated by the Local Authority excluding delegated Central
Government functions to Local Authorities.
Page | 3
--- Page 10 ---

In [49]:
wdc_functions = [
    [
        1,
        "Prepare annual Ward Development Plans",
        "WDC function",
        "Official PDF",
        wdc_guidelines_url
    ],
    [
        2,
        "Collect revenue when appointed by the Local Authority",
        "WDC function",
        "Official PDF",
        wdc_guidelines_url
    ],
    [
        3,
        "Monitor and evaluate development projects implemented in the ward",
        "WDC function",
        "Official PDF",
        wdc_guidelines_url
    ],
    [
        4,
        "Promote community engagement in development activities",
        "WDC function",
        "Official PDF",
        wdc_guidelines_url
    ],
    [
        5,
        "Formulate and submit project lists and CDF budget proposals",
        "WDC function",
        "Official PDF",
        wdc_guidelines_url
    ],
    [
        6,
        "Support research and development activities in the ward",
        "WDC function",
        "Official PDF",
        wdc_guidelines_url
    ],
    [
        7,
        "Identify investment opportunities within the ward",
        "WDC function",
        "Official PDF",
        wdc_guidelines_url
    ],
    [
        8,
        "Support resource co-management within the ward",
        "WDC function",
        "Official PDF",
        wdc_guidelines_url
    ],
    [
        9,
        "Promote dialogue and coordination among stakeholders",
        "WDC function",
        "Official PDF",
        wdc_guidelines_url
    ],
    [
        10,
        "Participate in capacity building activities",
        "WDC function",
        "Official PDF",
        wdc_guidelines_url
    ],
    [
        11,
        "Support urban renewal and development activities",
        "WDC function",
        "Official PDF",
        wdc_guidelines_url
    ],
    [
        12,
        "Identify potential sources of revenue for the ward",
        "WDC function",
        "Official PDF",
        wdc_guidelines_url
    ],
    [
        13,
        "Manage and keep records of resources allocated to the WDC",
        "WDC function",
        "Official PDF",
        wdc_guidelines_url
    ],
    [
        14,
        "Prepare and submit quarterly reports",
        "WDC function",
        "Official PDF",
        wdc_guidelines_url
    ],
    [
        15,
        "Maintain a ward database",
        "WDC function",
        "Official PDF",
        wdc_guidelines_url
    ],
    [
        16,
        "Execute other functions delegated by the Local Authority",
        "WDC function",
        "Official PDF",
        wdc_guidelines_url
    ]
]

wdc_functions_df = pd.DataFrame(
    wdc_functions,
    columns=[
        "function_number",
        "function",
        "category",
        "source_type",
        "source_url"
    ]
)

display(wdc_functions_df)

,function_number,function,category,source_type,source_url
0,1,Prepare annual Ward Development Plans,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
1,2,Collect revenue when appointed by the Local Au...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
2,3,Monitor and evaluate development projects impl...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
3,4,Promote community engagement in development ac...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
4,5,Formulate and submit project lists and CDF bud...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
5,6,Support research and development activities in...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
6,7,Identify investment opportunities within the ward,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
7,8,Support resource co-management within the ward,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
8,9,Promote dialogue and coordination among stakeh...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
9,10,Participate in capacity building activities,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
10,11,Support urban renewal and development activities,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
11,12,Identify potential sources of revenue for the ...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
12,13,Manage and keep records of resources allocated...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
13,14,Prepare and submit quarterly reports,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
14,15,Maintain a ward database,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
15,16,Execute other functions delegated by the Local...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...

In [50]:
print("Number of WDC functions:", len(wdc_functions_df))

print()
print("Missing values:")
print(wdc_functions_df.isnull().sum())

print()
print("Duplicate rows:", wdc_functions_df.duplicated().sum())

print()
print("Duplicate function numbers:",
      wdc_functions_df["function_number"].duplicated().sum())

Number of WDC functions: 16

Missing values:
function_number    0
function           0
category           0
source_type        0
source_url         0
dtype: int64

Duplicate rows: 0

Duplicate function numbers: 0

In [51]:
search_url = "https://www.kabwecouncil.gov.zm/"

search_response = requests.get(
    search_url,
    timeout=30,
    verify=False
)

search_soup = BeautifulSoup(
    search_response.text,
    "html.parser"
)

ward_related_links = []

for link in search_soup.find_all("a", href=True):
    link_text = link.get_text(" ", strip=True)
    href = link["href"]

    combined_text = f"{link_text} {href}".lower()

    if (
        "ward" in combined_text
        or "constituency" in combined_text
        or "kabw e central" in combined_text
        or "bwacha" in combined_text
    ):
        ward_related_links.append([
            link_text,
            href
        ])

print("Potential ward/constituency links:")
print("----------------------------------")

for link_text, href in ward_related_links:
    print("Text:", link_text)
    print("URL:", href)
    print()

Potential ward/constituency links:
----------------------------------
Text: Bwacha
URL: https://www.kabwecouncil.gov.zm/?page_id=2613

Text: Bwacha
URL: https://www.kabwecouncil.gov.zm/?page_id=2613

Text: Bwacha
URL: https://www.kabwecouncil.gov.zm/?page_id=2610

In [52]:
bwacha_url = "https://www.kabwecouncil.gov.zm/?page_id=2613"

bwacha_response = requests.get(
    bwacha_url,
    timeout=30,
    verify=False
)

print("Status code:", bwacha_response.status_code)
print("Content type:", bwacha_response.headers.get("Content-Type"))

bwacha_soup = BeautifulSoup(
    bwacha_response.text,
    "html.parser"
)

bwacha_text = bwacha_soup.get_text(
    separator="\n",
    strip=True
)

print()
print("Bwacha constituency page:")
print("-------------------------")
print(bwacha_text[:7000])

Status code: 200
Content type: text/html; charset=UTF-8

Bwacha constituency page:
-------------------------
Bwacha – Kabwe Municipal Council
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Search
BWACHA
Cllr.Njovu Jacob
Cllr.
Cllr.Tembo Louis
Cllr.Mumba Moses
Cllr.Hamiyanda Jupiter M
Cllr.Mumba Golden
Cllr.Mwata Evans
Contact Information
Kabwe Municipal Council
Central Province, Zambia
Tel: 260 215 224 238
P.O Box: 80424
Email: kabwemunicipalcouncil@gmail.com
Complaint
Follow Us
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
SMART Zambia
©2023. SMART Zambia Institute. All Rights Reserved.

In [54]:
kabwe_central_url = "https://www.kabwecouncil.gov.zm/?page_id=2610"

kabwe_central_response = requests.get(
    kabwe_central_url,
    timeout=30,
    verify=False
)

print("Status code:", kabwe_central_response.status_code)
print("Content type:", kabwe_central_response.headers.get("Content-Type"))

kabwe_central_soup = BeautifulSoup(
    kabwe_central_response.text,
    "html.parser"
)

kabwe_central_text = kabwe_central_soup.get_text(
    separator="\n",
    strip=True
)

print()
print("Kabwe Central constituency page:")
print("---------------------------------")
print(kabwe_central_text[:7000])

Status code: 200
Content type: text/html; charset=UTF-8

Kabwe Central constituency page:
---------------------------------
Kabwe Central – Kabwe Municipal Council
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Search
KABWE CENTRAL
Cllr.Phiri Wesley
Cllr.Ng'ambi Lester
Cllr.Musabila Eric
Cllr.Chileshe Emmanuel
Cllr.Belemu Sibanze
Contact Information
Kabwe Municipal Council
Central Province, Zambia
Tel: 260 215 224 238
P.O Box: 80424
Email: kabwemunicipalcouncil@gmail.com
Complaint
Follow Us
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
SMART Zambia
©2023. SMART Zambia Institute. All Rights Reserved.

In [55]:
search_terms = [
    "29 wards",
    "14 wards",
    "15 wards",
    "twenty-nine wards",
    "fourteen wards",
    "fifteen wards"
]

ward_count_results = []

for term in search_terms:
    search_response = requests.get(
        search_url,
        timeout=30,
        verify=False
    )

    search_soup = BeautifulSoup(
        search_response.text,
        "html.parser"
    )

    for link in search_soup.find_all("a", href=True):
        link_text = link.get_text(" ", strip=True)
        href = link["href"]

        combined_text = f"{link_text} {href}".lower()

        if term.lower() in combined_text:
            ward_count_results.append([
                term,
                link_text,
                href
            ])

print("Potential ward-count references:")
print("--------------------------------")

if ward_count_results:
    for result in ward_count_results:
        print("Search term:", result[0])
        print("Link text:", result[1])
        print("URL:", result[2])
        print()
else:
    print("No direct ward-count references found on the homepage links.")

Potential ward-count references:
--------------------------------
No direct ward-count references found on the homepage links.

In [56]:
search_pages = [
    "https://www.kabwecouncil.gov.zm/",
    "https://www.kabwecouncil.gov.zm/?page_id=2610",
    "https://www.kabwecouncil.gov.zm/?page_id=2613",
    "https://www.kabwecouncil.gov.zm/?page_id=2173"
]

ward_search_terms = [
    "29 wards",
    "29 ward",
    "twenty-nine wards",
    "twenty nine wards",
    "14 wards",
    "15 wards",
    "fourteen wards",
    "fifteen wards"
]

found_ward_references = []

for page_url in search_pages:

    response = requests.get(
        page_url,
        timeout=30,
        verify=False
    )

    soup = BeautifulSoup(
        response.text,
        "html.parser"
    )

    page_text = soup.get_text(
        separator=" ",
        strip=True
    )

    page_text_lower = page_text.lower()

    for term in ward_search_terms:
        if term.lower() in page_text_lower:
            found_ward_references.append([
                term,
                page_url
            ])

print("Ward-count references found:")
print("-----------------------------")

if found_ward_references:
    for term, page_url in found_ward_references:
        print("Term:", term)
        print("Page:", page_url)
        print()
else:
    print("No direct ward-count references found in the tested pages.")

Ward-count references found:
-----------------------------
No direct ward-count references found in the tested pages.

## Step 2.36 — Ward Count Data Limitation

The official Kabwe Municipal Council website provides separate pages for
Kabwe Central Constituency and Bwacha Constituency. However, the extracted
content from these pages lists councillors but does not explicitly state
the number of wards in each constituency.

Several official council webpages were searched for direct references to:

- 29 wards;
- 14 wards;
- 15 wards;
- twenty-nine wards;
- fourteen wards; and
- fifteen wards.

No direct ward-count statement was found in the webpages tested.

Therefore, constituency ward counts will **not be inferred** from the
available information. The dataset will retain the verified figure of
29 Ward Development Committees from the official 2025 Output Based Annual
Budget without converting this figure into an unsupported ward count.

This approach preserves data accuracy and prevents unsupported assumptions
from entering the dataset.

In [57]:
print("Number of general WDC records:", len(wdc_general_df))

print()
print("Missing values:")
print(wdc_general_df.isnull().sum())

print()
print("Duplicate rows:", wdc_general_df.duplicated().sum())

print()
print("General WDC information:")
display(wdc_general_df)

Number of general WDC records: 8

Missing values:
field          0
value          0
category       0
source_type    0
source_url     0
dtype: int64

Duplicate rows: 0

General WDC information:

,field,value,category,source_type,source_url
0,WDC abbreviation,WDC,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
1,WDC meaning,Ward Development Committee,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
2,WDC role,Grassroots link between communities and Local ...,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
3,WDC coverage,Formed in each ward,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
4,WDC membership selection,Residents select representatives through an el...,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
5,WDC nature,Nonpartisan committee,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
6,WDC purpose,Steering the developmental agenda at the grass...,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
7,WDC election oversight,Elective process overseen by the Local Authority,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173

In [58]:
print("Number of representative records:", len(wdc_representatives_df))

print()
print("Missing values:")
print(wdc_representatives_df.isnull().sum())

print()
print("Duplicate rows:", wdc_representatives_df.duplicated().sum())

print()
print("Duplicate wards:",
      wdc_representatives_df["ward"].duplicated().sum())

print()
print("WDC representative information:")
display(wdc_representatives_df)

Number of representative records: 3

Missing values:
ward           0
position       0
person         0
source_type    0
source_url     0
dtype: int64

Duplicate rows: 0

Duplicate wards: 0

WDC representative information:

,ward,position,person,source_type,source_url
0,Makululu,WDC Chairperson,Thomson Halwembe,Official webpage,https://www.kabwecouncil.gov.zm/?p=4873
1,Njanji,WDC Chairperson,Agness Mboma,Official webpage,https://www.kabwecouncil.gov.zm/?p=4873
2,Lwasanse,Ward Chairperson,Macmillan Chilangisha,Official webpage,https://www.kabwecouncil.gov.zm/?p=4873

In [59]:
print("Number of WDC statistic records:", len(wdc_statistics_df))

print()
print("Missing values:")
print(wdc_statistics_df.isnull().sum())

print()
print("Duplicate rows:", wdc_statistics_df.duplicated().sum())

print()
print("WDC statistics:")
display(wdc_statistics_df)

Number of WDC statistic records: 3

Missing values:
field          0
value          0
category       0
source_type    0
source_url     0
dtype: int64

Duplicate rows: 0

WDC statistics:

,field,value,category,source_type,source_url
0,Number of Ward Development Committees,29,Ward Development Committee statistics,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
1,Number of WDCs oriented,29,Ward Development Committee statistics,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
2,Number of quarterly WDC meetings planned,4,Ward Development Committee statistics,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...

In [60]:
wdc_functions_standardized_df = wdc_functions_df.copy()

wdc_functions_standardized_df = wdc_functions_standardized_df.rename(
    columns={
        "function_number": "field",
        "function": "value"
    }
)

wdc_functions_standardized_df["field"] = (
    "WDC Function " +
    wdc_functions_standardized_df["field"].astype(str)
)

print("Standardized WDC functions:")
display(wdc_functions_standardized_df)

Standardized WDC functions:

,field,value,category,source_type,source_url
0,WDC Function 1,Prepare annual Ward Development Plans,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
1,WDC Function 2,Collect revenue when appointed by the Local Au...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
2,WDC Function 3,Monitor and evaluate development projects impl...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
3,WDC Function 4,Promote community engagement in development ac...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
4,WDC Function 5,Formulate and submit project lists and CDF bud...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
5,WDC Function 6,Support research and development activities in...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
6,WDC Function 7,Identify investment opportunities within the ward,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
7,WDC Function 8,Support resource co-management within the ward,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
8,WDC Function 9,Promote dialogue and coordination among stakeh...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
9,WDC Function 10,Participate in capacity building activities,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
10,WDC Function 11,Support urban renewal and development activities,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
11,WDC Function 12,Identify potential sources of revenue for the ...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
12,WDC Function 13,Manage and keep records of resources allocated...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
13,WDC Function 14,Prepare and submit quarterly reports,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
14,WDC Function 15,Maintain a ward database,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
15,WDC Function 16,Execute other functions delegated by the Local...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...

In [61]:
wdc_representatives_standardized_df = wdc_representatives_df.copy()

wdc_representatives_standardized_df = wdc_representatives_standardized_df.rename(
    columns={
        "position": "field",
        "person": "value"
    }
)

wdc_representatives_standardized_df["field"] = (
    wdc_representatives_standardized_df["field"] +
    " - " +
    wdc_representatives_standardized_df["ward"]
)

wdc_representatives_standardized_df["category"] = "WDC representative"

wdc_representatives_standardized_df = (
    wdc_representatives_standardized_df[
        [
            "field",
            "value",
            "category",
            "source_type",
            "source_url"
        ]
    ]
)

print("Standardized WDC representative information:")
display(wdc_representatives_standardized_df)

Standardized WDC representative information:

,field,value,category,source_type,source_url
0,WDC Chairperson - Makululu,Thomson Halwembe,WDC representative,Official webpage,https://www.kabwecouncil.gov.zm/?p=4873
1,WDC Chairperson - Njanji,Agness Mboma,WDC representative,Official webpage,https://www.kabwecouncil.gov.zm/?p=4873
2,Ward Chairperson - Lwasanse,Macmillan Chilangisha,WDC representative,Official webpage,https://www.kabwecouncil.gov.zm/?p=4873

In [62]:
wdc_statistics_standardized_df = wdc_statistics_df.copy()

print("Standardized WDC statistics:")
display(wdc_statistics_standardized_df)

Standardized WDC statistics:

,field,value,category,source_type,source_url
0,Number of Ward Development Committees,29,Ward Development Committee statistics,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
1,Number of WDCs oriented,29,Ward Development Committee statistics,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
2,Number of quarterly WDC meetings planned,4,Ward Development Committee statistics,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...

In [63]:
wdc_combined_df = pd.concat(
    [
        wdc_general_df,
        wdc_statistics_standardized_df,
        wdc_functions_standardized_df,
        wdc_representatives_standardized_df
    ],
    ignore_index=True
)

print("Total WDC records:", len(wdc_combined_df))
print()
print("Columns:")
print(list(wdc_combined_df.columns))

print()
print("Combined WDC dataset:")
display(wdc_combined_df)

Total WDC records: 30

Columns:
['field', 'value', 'category', 'source_type', 'source_url']

Combined WDC dataset:

,field,value,category,source_type,source_url
0,WDC abbreviation,WDC,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
1,WDC meaning,Ward Development Committee,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
2,WDC role,Grassroots link between communities and Local ...,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
3,WDC coverage,Formed in each ward,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
4,WDC membership selection,Residents select representatives through an el...,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
5,WDC nature,Nonpartisan committee,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
6,WDC purpose,Steering the developmental agenda at the grass...,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
7,WDC election oversight,Elective process overseen by the Local Authority,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
8,Number of Ward Development Committees,29,Ward Development Committee statistics,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
9,Number of WDCs oriented,29,Ward Development Committee statistics,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
10,Number of quarterly WDC meetings planned,4,Ward Development Committee statistics,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
11,WDC Function 1,Prepare annual Ward Development Plans,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
12,WDC Function 2,Collect revenue when appointed by the Local Au...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
13,WDC Function 3,Monitor and evaluate development projects impl...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
14,WDC Function 4,Promote community engagement in development ac...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
15,WDC Function 5,Formulate and submit project lists and CDF bud...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
16,WDC Function 6,Support research and development activities in...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
17,WDC Function 7,Identify investment opportunities within the ward,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
18,WDC Function 8,Support resource co-management within the ward,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
19,WDC Function 9,Promote dialogue and coordination among stakeh...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
20,WDC Function 10,Participate in capacity building activities,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
21,WDC Function 11,Support urban renewal and development activities,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
22,WDC Function 12,Identify potential sources of revenue for the ...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
23,WDC Function 13,Manage and keep records of resources allocated...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
24,WDC Function 14,Prepare and submit quarterly reports,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
25,WDC Function 15,Maintain a ward database,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
26,WDC Function 16,Execute other functions delegated by the Local...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
27,WDC Chairperson - Makululu,Thomson Halwembe,WDC representative,Official webpage,https://www.kabwecouncil.gov.zm/?p=4873
28,WDC Chairperson - Njanji,Agness Mboma,WDC representative,Official webpage,https://www.kabwecouncil.gov.zm/?p=4873
29,Ward Chairperson - Lwasanse,Macmillan Chilangisha,WDC representative,Official webpage,https://www.kabwecouncil.gov.zm/?p=4873

In [64]:
print("Total records:", len(wdc_combined_df))

print()
print("Missing values:")
print(wdc_combined_df.isnull().sum())

print()
print("Duplicate rows:", wdc_combined_df.duplicated().sum())

print()
print("Records by category:")
print(wdc_combined_df["category"].value_counts())

print()
print("Source types:")
print(wdc_combined_df["source_type"].value_counts())

Total records: 30

Missing values:
field          0
value          0
category       0
source_type    0
source_url     0
dtype: int64

Duplicate rows: 0

Records by category:
category
WDC function                             16
Ward Development Committee                8
Ward Development Committee statistics     3
WDC representative                        3
Name: count, dtype: int64

Source types:
source_type
Official PDF        19
Official webpage    11
Name: count, dtype: int64

In [65]:
text_columns = [
    "field",
    "value",
    "category",
    "source_type",
    "source_url"
]

for column in text_columns:
    wdc_combined_df[column] = (
        wdc_combined_df[column]
        .astype(str)
        .str.strip()
    )

print("Text cleaning completed.")

print()
print("Sample of cleaned data:")
display(wdc_combined_df.head(10))

Text cleaning completed.

Sample of cleaned data:

,field,value,category,source_type,source_url
0,WDC abbreviation,WDC,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
1,WDC meaning,Ward Development Committee,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
2,WDC role,Grassroots link between communities and Local ...,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
3,WDC coverage,Formed in each ward,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
4,WDC membership selection,Residents select representatives through an el...,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
5,WDC nature,Nonpartisan committee,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
6,WDC purpose,Steering the developmental agenda at the grass...,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
7,WDC election oversight,Elective process overseen by the Local Authority,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
8,Number of Ward Development Committees,29,Ward Development Committee statistics,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
9,Number of WDCs oriented,29,Ward Development Committee statistics,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...

In [66]:
duplicate_count = wdc_combined_df.duplicated().sum()

print("Duplicate rows after cleaning:", duplicate_count)

if duplicate_count == 0:
    print("✓ No duplicate records found.")
else:
    print("Duplicate records found:")
    display(
        wdc_combined_df[
            wdc_combined_df.duplicated(keep=False)
        ]
    )

Duplicate rows after cleaning: 0
✓ No duplicate records found.

In [67]:
print("Data types:")
print(wdc_combined_df.dtypes)

print()
print("Dataset shape:")
print(wdc_combined_df.shape)

Data types:
field          str
value          str
category       str
source_type    str
source_url     str
dtype: object

Dataset shape:
(30, 5)

In [68]:
wdc_output_file = "db-unza26-csc4792-ward-development-committees.csv"

wdc_combined_df.to_csv(
    wdc_output_file,
    sep="|",
    index=False
)

print("CSV file created successfully:")
print(wdc_output_file)

CSV file created successfully:
db-unza26-csc4792-ward-development-committees.csv

In [69]:
wdc_check_df = pd.read_csv(
    wdc_output_file,
    sep="|"
)

print("CSV successfully read back.")

print()
print("Shape:", wdc_check_df.shape)

print()
print("Columns:")
print(list(wdc_check_df.columns))

print()
print("First 10 records:")
display(wdc_check_df.head(10))

CSV successfully read back.

Shape: (30, 5)

Columns:
['field', 'value', 'category', 'source_type', 'source_url']

First 10 records:

,field,value,category,source_type,source_url
0,WDC abbreviation,WDC,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
1,WDC meaning,Ward Development Committee,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
2,WDC role,Grassroots link between communities and Local ...,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
3,WDC coverage,Formed in each ward,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
4,WDC membership selection,Residents select representatives through an el...,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
5,WDC nature,Nonpartisan committee,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
6,WDC purpose,Steering the developmental agenda at the grass...,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
7,WDC election oversight,Elective process overseen by the Local Authority,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
8,Number of Ward Development Committees,29,Ward Development Committee statistics,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
9,Number of WDCs oriented,29,Ward Development Committee statistics,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...

In [70]:
print("STEP 2 DATASET SUMMARY")
print("=======================")

print("Dataset name:")
print(wdc_output_file)

print()
print("Number of records:", len(wdc_check_df))
print("Number of columns:", len(wdc_check_df.columns))

print()
print("Columns:")
for column in wdc_check_df.columns:
    print("-", column)

print()
print("Records by category:")
print(wdc_check_df["category"].value_counts())

print()
print("Source types:")
print(wdc_check_df["source_type"].value_counts())

STEP 2 DATASET SUMMARY
=======================
Dataset name:
db-unza26-csc4792-ward-development-committees.csv

Number of records: 30
Number of columns: 5

Columns:
- field
- value
- category
- source_type
- source_url

Records by category:
category
WDC function                             16
Ward Development Committee                8
Ward Development Committee statistics     3
WDC representative                        3
Name: count, dtype: int64

Source types:
source_type
Official PDF        19
Official webpage    11
Name: count, dtype: int64

In [71]:
wdc_source_register = [
    [
        "Official FAQ",
        "Kabwe Municipal Council FAQ",
        faq_url
    ],
    [
        "2025 Output Based Annual Budget",
        "Kabwe Municipal Council 2025 Output Based Annual Budget",
        budget_url
    ],
    [
        "WDC Guidelines",
        "Guidelines on the Establishment, Management and Operation of Ward Development Committees",
        wdc_guidelines_url
    ],
    [
        "WDC Representatives Article",
        "Kabwe Municipal Council engages stakeholders on proposed new by-laws",
        article_url
    ],
    [
        "Kabwe Central Constituency Page",
        "Kabwe Municipal Council Kabwe Central constituency page",
        kabwe_central_url
    ],
    [
        "Bwacha Constituency Page",
        "Kabwe Municipal Council Bwacha constituency page",
        bwacha_url
    ]
]

wdc_source_register_df = pd.DataFrame(
    wdc_source_register,
    columns=[
        "source_type",
        "description",
        "source_url"
    ]
)

display(wdc_source_register_df)

,source_type,description,source_url
0,Official FAQ,Kabwe Municipal Council FAQ,https://www.kabwecouncil.gov.zm/?page_id=2173
1,2025 Output Based Annual Budget,Kabwe Municipal Council 2025 Output Based Annu...,https://www.kabwecouncil.gov.zm/wp-content/upl...
2,WDC Guidelines,"Guidelines on the Establishment, Management an...",https://www.kabwecouncil.gov.zm/wp-content/upl...
3,WDC Representatives Article,Kabwe Municipal Council engages stakeholders o...,https://www.kabwecouncil.gov.zm/?p=4873
4,Kabwe Central Constituency Page,Kabwe Municipal Council Kabwe Central constitu...,https://www.kabwecouncil.gov.zm/?page_id=2610
5,Bwacha Constituency Page,Kabwe Municipal Council Bwacha constituency page,https://www.kabwecouncil.gov.zm/?page_id=2613

In [72]:
print("SOURCE REGISTER VALIDATION")
print("==========================")

print("Number of sources:", len(wdc_source_register_df))
print()

print("Missing values:")
print(wdc_source_register_df.isnull().sum())
print()

print("Duplicate URLs:", wdc_source_register_df["source_url"].duplicated().sum())
print()

print("Expected number of sources: 6")

if (
    len(wdc_source_register_df) == 6
    and wdc_source_register_df.isnull().sum().sum() == 0
    and wdc_source_register_df["source_url"].duplicated().sum() == 0
):
    print("RESULT: Source register validation PASSED.")
else:
    print("RESULT: Source register validation FAILED.")

SOURCE REGISTER VALIDATION
==========================
Number of sources: 6

Missing values:
source_type    0
description    0
source_url     0
dtype: int64

Duplicate URLs: 0

Expected number of sources: 6
RESULT: Source register validation PASSED.

## Step 2.53 — Data Provenance

The Ward Development Committee dataset was compiled from official
Kabwe Municipal Council webpages and official council documents.

The sources were used as follows:

| Source | Purpose |
|---|---|
| Kabwe Municipal Council FAQ | Definition, role, coverage, membership selection, nature and purpose of WDCs |
| 2025 Output Based Annual Budget | Number of WDCs, number of WDCs oriented, and planned quarterly WDC meetings |
| WDC Guidelines | Functions of Ward Development Committees |
| WDC Representatives Article | Names and positions of selected WDC representatives |
| Kabwe Central Constituency Page | Checked for constituency and ward information |
| Bwacha Constituency Page | Checked for constituency and ward information |

Each dataset record contains a `source_url` column so that the
information can be traced back to its official source.

The Kabwe Central and Bwacha constituency pages were also examined when
investigating ward-count information. Since these pages did not provide
explicit ward counts, no constituency ward numbers were inferred.

This provenance approach ensures that the dataset contains only
information that could be supported by the available official sources.

In [73]:
print("FINAL DATASET QUALITY CHECK")
print("===========================")

print("Dataset:", wdc_output_file)
print("Rows:", len(wdc_check_df))
print("Columns:", len(wdc_check_df.columns))
print()

print("Missing values:")
print(wdc_check_df.isnull().sum())
print()

print("Duplicate records:", wdc_check_df.duplicated().sum())
print()

print("Pipe delimiter check:")
with open(wdc_output_file, "r", encoding="utf-8") as file:
    first_line = file.readline().strip()

print(first_line)

print()
print("Required columns:")
required_columns = [
    "field",
    "value",
    "category",
    "source_type",
    "source_url"
]

for column in required_columns:
    print(f"- {column}:", column in wdc_check_df.columns)

print()

if (
    len(wdc_check_df) == 30
    and len(wdc_check_df.columns) == 5
    and wdc_check_df.isnull().sum().sum() == 0
    and wdc_check_df.duplicated().sum() == 0
    and all(column in wdc_check_df.columns for column in required_columns)
    and "|" in first_line
):
    print("RESULT: FINAL DATASET QUALITY CHECK PASSED.")
else:
    print("RESULT: FINAL DATASET QUALITY CHECK FAILED.")

FINAL DATASET QUALITY CHECK
===========================
Dataset: db-unza26-csc4792-ward-development-committees.csv
Rows: 30
Columns: 5

Missing values:
field          0
value          0
category       0
source_type    0
source_url     0
dtype: int64

Duplicate records: 0

Pipe delimiter check:
field|value|category|source_type|source_url

Required columns:
- field: True
- value: True
- category: True
- source_type: True
- source_url: True

RESULT: FINAL DATASET QUALITY CHECK PASSED.

In [74]:
print("FINAL WARD DEVELOPMENT COMMITTEE DATASET")
print("=========================================")

display(wdc_check_df)

FINAL WARD DEVELOPMENT COMMITTEE DATASET
=========================================

,field,value,category,source_type,source_url
0,WDC abbreviation,WDC,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
1,WDC meaning,Ward Development Committee,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
2,WDC role,Grassroots link between communities and Local ...,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
3,WDC coverage,Formed in each ward,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
4,WDC membership selection,Residents select representatives through an el...,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
5,WDC nature,Nonpartisan committee,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
6,WDC purpose,Steering the developmental agenda at the grass...,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
7,WDC election oversight,Elective process overseen by the Local Authority,Ward Development Committee,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=2173
8,Number of Ward Development Committees,29,Ward Development Committee statistics,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
9,Number of WDCs oriented,29,Ward Development Committee statistics,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
10,Number of quarterly WDC meetings planned,4,Ward Development Committee statistics,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
11,WDC Function 1,Prepare annual Ward Development Plans,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
12,WDC Function 2,Collect revenue when appointed by the Local Au...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
13,WDC Function 3,Monitor and evaluate development projects impl...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
14,WDC Function 4,Promote community engagement in development ac...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
15,WDC Function 5,Formulate and submit project lists and CDF bud...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
16,WDC Function 6,Support research and development activities in...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
17,WDC Function 7,Identify investment opportunities within the ward,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
18,WDC Function 8,Support resource co-management within the ward,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
19,WDC Function 9,Promote dialogue and coordination among stakeh...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
20,WDC Function 10,Participate in capacity building activities,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
21,WDC Function 11,Support urban renewal and development activities,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
22,WDC Function 12,Identify potential sources of revenue for the ...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
23,WDC Function 13,Manage and keep records of resources allocated...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
24,WDC Function 14,Prepare and submit quarterly reports,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
25,WDC Function 15,Maintain a ward database,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
26,WDC Function 16,Execute other functions delegated by the Local...,WDC function,Official PDF,https://www.kabwecouncil.gov.zm/wp-content/upl...
27,WDC Chairperson - Makululu,Thomson Halwembe,WDC representative,Official webpage,https://www.kabwecouncil.gov.zm/?p=4873
28,WDC Chairperson - Njanji,Agness Mboma,WDC representative,Official webpage,https://www.kabwecouncil.gov.zm/?p=4873
29,Ward Chairperson - Lwasanse,Macmillan Chilangisha,WDC representative,Official webpage,https://www.kabwecouncil.gov.zm/?p=4873

# Step 2 — Completion Summary

## Ward Development Committee Information

This notebook extracted, cleaned, standardized, validated, and exported
information about Ward Development Committees associated with Kabwe
Municipal Council.

### Final dataset

**File name:**

`db-unza26-csc4792-ward-development-committees.csv`

**Delimiter:** `|`

**Records:** 30

**Columns:** 5

### Dataset columns

1. `field`
2. `value`
3. `category`
4. `source_type`
5. `source_url`

### Information included

The dataset contains information about:

- the meaning and role of Ward Development Committees;
- WDC coverage and membership selection;
- the nonpartisan nature and purpose of WDCs;
- the number of WDCs;
- the number of WDCs oriented;
- planned quarterly WDC meetings;
- WDC functions;
- identified WDC representatives; and
- official source URLs.

### Data quality

The final dataset was checked for:

- missing values;
- duplicate records;
- correct number of columns;
- required column names;
- correct pipe delimiter; and
- successful CSV read-back.

No unsupported constituency ward counts were inferred because the
official constituency pages examined did not provide explicit ward-count
information.

## Step 2 Status

**COMPLETE**

The resulting CSV file is ready to be used as the Ward Development
Committee component of the CSC4792 Kabwe Municipal Council dataset.