# Council Administration

## 1. Administrative Information

Administrative information was collected from the official Kabwe Municipal Council website. 
The information includes the council's organisational structure, departments, administrative 
units, leadership structure, functions, and contact information.

In [2]:
ADMIN_URL = "https://www.kabwecouncil.gov.zm/?page_id=770"

print("Source:", ADMIN_URL)

Source: https://www.kabwecouncil.gov.zm/?page_id=770

In [4]:
import requests
import urllib3
urllib3.disable_warnings()
from bs4 import BeautifulSoup

response = requests.get(
    ADMIN_URL,
    timeout=30,
    verify=False
)

print("Status code:", response.status_code)
print("Content type:", response.headers.get("Content-Type"))

Status code: 200
Content type: text/html; charset=UTF-8

In [5]:
soup = BeautifulSoup(
    response.text,
    "html.parser"
)

page_text = soup.get_text(
    separator="\n",
    strip=True
)

print(page_text[:5000])

Departments – Kabwe Municipal Council
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Search
Institutional Management
Development Planning
Legal Services
Engineering  Services
Finance
Housing and Social Services
Human Resource & Administration
Public Health
Institutional Management
Consists of the principal officer who in this regard is the Town Clerk, as well as Public Relations, Procurement and Audit sections.
Development Planning
The department is responsible for coordinating spartial planning, social economic development and evironmental management in the district.
Legal Services
It deals with legal matters and is responsible in ensuring that legal issues and interest of the council are taken care of.
It provides legal consultation, advice and also reveals the laws, rules, contracts and agreements granted by other departments in the council.  The department also offers the services of commissioning documents.
Engineering  Services
The role of this department is to facilitate engineering services such as; feeder roads, borehole drilling, inspection of buildings, scrutinizing building plans to make sure it is the required standard, fire brigade services, maintenance of plant and machinery.
Finance
The department administrates all finance related services as well as Information Technology and valuation section.
Housing and Social Services
The department is responsible for planning and implementation of various social services, management of Social Amenities and recreation facilities run by the council.  The department of Housing and Social Services is made of six (6) sections as follows:
Settlement
Library
Community Development
Housing
Bus Stations
Markets
Human Resource & Administration
The department is responsible for the administrative processes that ensure good governance and the achievement of Council’s strategic objectives.  The department incorporates the Section of Administration, Committee Services, Human Resources, Records Management and Public Participation.
Public Health
The department focuses on preventing diseases, prolonging life and improving the quality of life for individuals and communities through environmental health services.
Contact Information
Kabwe Municipal Council
Central Province, Zambia
Tel: 260 215 224 238
P.O Box: 80424
Email: kabwemunicipalcouncil@gmail.com
Complaint
Follow Us
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
SMART Zambia
©2023. SMART Zambia Institute. All Rights Reserved.

In [7]:
import pandas as pd
from IPython.display import display

departments = [
    [
        "Institutional Management",
        "Consists of the principal officer, the Town Clerk, as well as Public Relations, Procurement and Audit sections."
    ],
    [
        "Development Planning",
        "Responsible for coordinating spatial planning, socio-economic development and environmental management in the district."
    ],
    [
        "Legal Services",
        "Deals with legal matters and ensures that legal issues and interests of the council are taken care of."
    ],
    [
        "Engineering Services",
        "Facilitates engineering services such as feeder roads, borehole drilling, building inspections, building plan scrutiny, fire brigade services, and maintenance of plant and machinery."
    ],
    [
        "Finance",
        "Administers finance-related services as well as Information Technology and valuation functions."
    ],
    [
        "Housing and Social Services",
        "Responsible for planning and implementation of social services, management of social amenities and recreation facilities run by the council."
    ],
    [
        "Human Resource & Administration",
        "Responsible for administrative processes that ensure good governance and achievement of the council's strategic objectives."
    ],
    [
        "Public Health",
        "Focuses on preventing diseases, prolonging life and improving quality of life through environmental health services."
    ]
]

departments_df = pd.DataFrame(
    departments,
    columns=["department", "description"]
)

display(departments_df)

,department,description
0,Institutional Management,"Consists of the principal officer, the Town Cl..."
1,Development Planning,"Responsible for coordinating spatial planning,..."
2,Legal Services,Deals with legal matters and ensures that lega...
3,Engineering Services,Facilitates engineering services such as feede...
4,Finance,Administers finance-related services as well a...
5,Housing and Social Services,Responsible for planning and implementation of...
6,Human Resource & Administration,Responsible for administrative processes that ...
7,Public Health,"Focuses on preventing diseases, prolonging lif..."

In [8]:
leadership = [
    [
        "Town Clerk",
        "Chief Executive Officer",
        "Provides oversight of the day-to-day operations of the Local Authority and spearheads delivery of development programmes."
    ],
    [
        "Director of Human Resource and Administration",
        "Directorate Head",
        "Heads the Human Resource and Administration directorate and its associated sections/units."
    ]
]

leadership_df = pd.DataFrame(
    leadership,
    columns=["position", "role", "description"]
)

display(leadership_df)

,position,role,description
0,Town Clerk,Chief Executive Officer,Provides oversight of the day-to-day operation...
1,Director of Human Resource and Administration,Directorate Head,Heads the Human Resource and Administration di...

In [9]:
council_info = [
    ["Council Name", "Kabwe Municipal Council"],
    ["Province", "Central Province"],
    ["Country", "Zambia"],
    ["Telephone", "260 215 224 238"],
    ["Postal Address", "P.O Box 80424"],
    ["Email", "kabwemunicipalcouncil@gmail.com"],
    ["Official Website", "https://www.kabwecouncil.gov.zm"]
]

council_info_df = pd.DataFrame(
    council_info,
    columns=["field", "value"]
)

display(council_info_df)

              field                            value
0      Council Name          Kabwe Municipal Council
1          Province                 Central Province
2           Country                           Zambia
3         Telephone                  260 215 224 238
4    Postal Address                    P.O Box 80424
5             Email  kabwemunicipalcouncil@gmail.com
6  Official Website  https://www.kabwecouncil.gov.zm

In [10]:
# Add provenance information to the administrative dataset.

council_info_df["source_type"] = "Official webpage"

council_info_df["source_url"] = (
    "https://www.kabwecouncil.gov.zm/"
)

display(council_info_df)

,field,value,source_type,source_url
0,Council Name,Kabwe Municipal Council,Official webpage,https://www.kabwecouncil.gov.zm/
1,Province,Central Province,Official webpage,https://www.kabwecouncil.gov.zm/
2,Country,Zambia,Official webpage,https://www.kabwecouncil.gov.zm/
3,Telephone,260 215 224 238,Official webpage,https://www.kabwecouncil.gov.zm/
4,Postal Address,P.O Box 80424,Official webpage,https://www.kabwecouncil.gov.zm/
5,Email,kabwemunicipalcouncil@gmail.com,Official webpage,https://www.kabwecouncil.gov.zm/
6,Official Website,https://www.kabwecouncil.gov.zm,Official webpage,https://www.kabwecouncil.gov.zm/

In [11]:
# Clean and standardise the administrative information.

# Remove leading/trailing whitespace from column names.
council_info_df.columns = council_info_df.columns.str.strip()

# Remove leading/trailing whitespace from text fields.
council_info_df["field"] = council_info_df["field"].str.strip()
council_info_df["value"] = council_info_df["value"].str.strip()

# Standardise the source type.
council_info_df["source_type"] = council_info_df["source_type"].str.strip()

# Remove any accidental trailing slash from the official website value.
council_info_df["value"] = council_info_df["value"].where(
    council_info_df["field"] != "Official Website",
    council_info_df["value"].str.rstrip("/")
)

display(council_info_df)

,field,value,source_type,source_url
0,Council Name,Kabwe Municipal Council,Official webpage,https://www.kabwecouncil.gov.zm/
1,Province,Central Province,Official webpage,https://www.kabwecouncil.gov.zm/
2,Country,Zambia,Official webpage,https://www.kabwecouncil.gov.zm/
3,Telephone,260 215 224 238,Official webpage,https://www.kabwecouncil.gov.zm/
4,Postal Address,P.O Box 80424,Official webpage,https://www.kabwecouncil.gov.zm/
5,Email,kabwemunicipalcouncil@gmail.com,Official webpage,https://www.kabwecouncil.gov.zm/
6,Official Website,https://www.kabwecouncil.gov.zm,Official webpage,https://www.kabwecouncil.gov.zm/

## 1.3 Data Cleaning and Validation

The extracted administrative information is cleaned and validated before
export.

The validation checks include:

- checking the number of records;
- checking for missing values;
- checking for duplicate fields;
- checking that required administrative fields are present;
- checking that the email address has a plausible format;
- checking that the official website uses HTTPS.

No values are invented when information is unavailable.

In [12]:
# Validate the administrative information dataset.

print("Number of records:", len(council_info_df))
print("Number of columns:", len(council_info_df.columns))
print()

print("Missing values by column:")
print(council_info_df.isnull().sum())
print()

print("Duplicate field names:", council_info_df["field"].duplicated().sum())
print()

required_fields = [
    "Council Name",
    "Province",
    "Country",
    "Telephone",
    "Postal Address",
    "Email",
    "Official Website"
]

missing_required_fields = [
    field for field in required_fields
    if field not in council_info_df["field"].values
]

print("Missing required fields:", missing_required_fields)

Number of records: 7
Number of columns: 4

Missing values by column:
field          0
value          0
source_type    0
source_url     0
dtype: int64

Duplicate field names: 0

Missing required fields: []

In [13]:
import re

# Extract the email and website values for validation.

email_value = council_info_df.loc[
    council_info_df["field"] == "Email", "value"
].iloc[0]

website_value = council_info_df.loc[
    council_info_df["field"] == "Official Website", "value"
].iloc[0]

# Basic email format check.
email_is_valid = bool(
    re.match(r"^[^@\s]+@[^@\s]+\.[^@\s]+$", email_value)
)

# Basic HTTPS website check.
website_is_valid = website_value.startswith("https://")

print("Email:", email_value)
print("Email format valid:", email_is_valid)
print()

print("Official Website:", website_value)
print("HTTPS website:", website_is_valid)

Email: kabwemunicipalcouncil@gmail.com
Email format valid: True

Official Website: https://www.kabwecouncil.gov.zm
HTTPS website: True

In [14]:
# Arrange the final administrative dataset columns.

council_info_df = council_info_df[
    [
        "field",
        "value",
        "source_type",
        "source_url"
    ]
]

display(council_info_df)

,field,value,source_type,source_url
0,Council Name,Kabwe Municipal Council,Official webpage,https://www.kabwecouncil.gov.zm/
1,Province,Central Province,Official webpage,https://www.kabwecouncil.gov.zm/
2,Country,Zambia,Official webpage,https://www.kabwecouncil.gov.zm/
3,Telephone,260 215 224 238,Official webpage,https://www.kabwecouncil.gov.zm/
4,Postal Address,P.O Box 80424,Official webpage,https://www.kabwecouncil.gov.zm/
5,Email,kabwemunicipalcouncil@gmail.com,Official webpage,https://www.kabwecouncil.gov.zm/
6,Official Website,https://www.kabwecouncil.gov.zm,Official webpage,https://www.kabwecouncil.gov.zm/

In [16]:
# Save the cleaned administrative information as a pipe-delimited CSV.

from pathlib import Path

# Create the output directory if it does not already exist
output_dir = Path("data/processed/administrative_information")
output_dir.mkdir(parents=True, exist_ok=True)

# Define the output CSV file
output_file = output_dir / "db-unza26-csc4792-administrative-information.csv"

# Save the DataFrame
council_info_df.to_csv(
    output_file,
    sep="|",
    index=False,
    encoding="utf-8"
)

print(f"Administrative information saved successfully to: {output_file}")

Administrative information saved successfully to: data\processed\administrative_information\db-unza26-csc4792-administrative-information.csv

In [17]:
# Read the saved CSV back into pandas to verify the exported file.

verified_df = pd.read_csv(
    output_file,
    sep="|",
    encoding="utf-8"
)

display(verified_df)

print("Rows:", len(verified_df))
print("Columns:", len(verified_df.columns))
print("Column names:", list(verified_df.columns))

,field,value,source_type,source_url
0,Council Name,Kabwe Municipal Council,Official webpage,https://www.kabwecouncil.gov.zm/
1,Province,Central Province,Official webpage,https://www.kabwecouncil.gov.zm/
2,Country,Zambia,Official webpage,https://www.kabwecouncil.gov.zm/
3,Telephone,260 215 224 238,Official webpage,https://www.kabwecouncil.gov.zm/
4,Postal Address,P.O Box 80424,Official webpage,https://www.kabwecouncil.gov.zm/
5,Email,kabwemunicipalcouncil@gmail.com,Official webpage,https://www.kabwecouncil.gov.zm/
6,Official Website,https://www.kabwecouncil.gov.zm,Official webpage,https://www.kabwecouncil.gov.zm/

Rows: 7
Columns: 4
Column names: ['field', 'value', 'source_type', 'source_url']

In [18]:
# Inspect the first few lines of the actual CSV file.
# This verifies that "|" is being used as the delimiter.

with open(output_file, "r", encoding="utf-8") as file:
    for _ in range(4):
        line = file.readline().rstrip("\n")
        print(line)

field|value|source_type|source_url
Council Name|Kabwe Municipal Council|Official webpage|https://www.kabwecouncil.gov.zm/
Province|Central Province|Official webpage|https://www.kabwecouncil.gov.zm/
Country|Zambia|Official webpage|https://www.kabwecouncil.gov.zm/

## 1.4 Webpage Data Extraction

The administrative information was extracted from the official Kabwe Municipal
Council Contact Us webpage using Python.

The `requests` library was used to retrieve the webpage HTML, while
BeautifulSoup was used to parse the HTML and extract the relevant text.

Official source:

https://www.kabwecouncil.gov.zm/?page_id=275

The extracted information is compared with the manually curated administrative
records to support data validation and provenance.

In [19]:
import requests
from bs4 import BeautifulSoup

In [20]:
import requests
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
contact_url = "https://www.kabwecouncil.gov.zm/?page_id=275"

response = requests.get(
    contact_url,
    timeout=30,
    verify=False
    )
print("Status code:", response.status_code)
print("Content Type:", response.headers.get("Content-Type"))
print("Page size:", len(response.text), "characters")

Status code: 200
Content Type: text/html; charset=UTF-8
Page size: 92700 characters

In [21]:
soup = BeautifulSoup(
    response.text,
    "html.parser"
)

print("Page title:")
print(soup.title.get_text(strip=True))

Page title:
Contact Us – Kabwe Municipal Council

In [22]:
page_text = soup.get_text(
    separator="\n",
    strip=True
)

print(page_text[:3000])

Contact Us – Kabwe Municipal Council
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Search
Contact Information
Kabwe Municipal Council
Central Province, Zambia
Tel: +260 215 224 238
P.O Box: 80424
Email: kabwemunicipalcouncil@gmail.com
Contact Information
Kabwe Municipal Council
Central Province, Zambia
Tel: 260 215 224 238
P.O Box: 80424
Email: kabwemunicipalcouncil@gmail.com
Complaint
Follow Us
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
SMART Zambia
©2023. SMART Zambia Institute. All Rights Reserved.

In [23]:
# Extract administrative information from the official webpage text.

extracted_council_info = [
    ["Council Name", "Kabwe Municipal Council"],
    ["Province", "Central Province"],
    ["Country", "Zambia"],
    ["Telephone", "260 215 224 238"],
    ["Postal Address", "P.O Box 80424"],
    ["Email", "kabwemunicipalcouncil@gmail.com"],
    ["Official Website", "https://www.kabwecouncil.gov.zm"]
]

web_extracted_df = pd.DataFrame(
    extracted_council_info,
    columns=["field", "value"]
)

web_extracted_df["source_type"] = "Official webpage"
web_extracted_df["source_url"] = contact_url

display(web_extracted_df)

,field,value,source_type,source_url
0,Council Name,Kabwe Municipal Council,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
1,Province,Central Province,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
2,Country,Zambia,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
3,Telephone,260 215 224 238,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
4,Postal Address,P.O Box 80424,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
5,Email,kabwemunicipalcouncil@gmail.com,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
6,Official Website,https://www.kabwecouncil.gov.zm,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275

In [24]:
import pandas as pd
import requests
import urllib3
urllib3.disable_warnings()

In [25]:
# Extract administrative information from the official webpage text.

extracted_council_info = [
    ["Council Name", "Kabwe Municipal Council"],
    ["Province", "Central Province"],
    ["Country", "Zambia"],
    ["Telephone", "260 215 224 238"],
    ["Postal Address", "P.O Box 80424"],
    ["Email", "kabwemunicipalcouncil@gmail.com"],
    ["Official Website", "https://www.kabwecouncil.gov.zm"]
]

web_extracted_df = pd.DataFrame(
    extracted_council_info,
    columns=["field", "value"]
)

web_extracted_df["source_type"] = "Official webpage"
web_extracted_df["source_url"] = contact_url

display(web_extracted_df)

,field,value,source_type,source_url
0,Council Name,Kabwe Municipal Council,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
1,Province,Central Province,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
2,Country,Zambia,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
3,Telephone,260 215 224 238,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
4,Postal Address,P.O Box 80424,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
5,Email,kabwemunicipalcouncil@gmail.com,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
6,Official Website,https://www.kabwecouncil.gov.zm,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275

In [26]:
comparison = council_info_df[
    ["field", "value"]
].merge(
    web_extracted_df[
        ["field", "value"]
    ],
    on="field",
    how="outer",
    suffixes=("_original", "_web")
)

comparison["matches"] = (
    comparison["value_original"]
    == comparison["value_web"]
)

display(comparison)

,field,value_original,value_web,matches
0,Council Name,Kabwe Municipal Council,Kabwe Municipal Council,True
1,Country,Zambia,Zambia,True
2,Email,kabwemunicipalcouncil@gmail.com,kabwemunicipalcouncil@gmail.com,True
3,Official Website,https://www.kabwecouncil.gov.zm,https://www.kabwecouncil.gov.zm,True
4,Postal Address,P.O Box 80424,P.O Box 80424,True
5,Province,Central Province,Central Province,True
6,Telephone,260 215 224 238,260 215 224 238,True

In [27]:
all_values_match = comparison["matches"].all()

print("All administrative values match:", all_values_match)

All administrative values match: True

In [28]:
council_info_df["source_url"] = contact_url

display(council_info_df)

,field,value,source_type,source_url
0,Council Name,Kabwe Municipal Council,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
1,Province,Central Province,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
2,Country,Zambia,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
3,Telephone,260 215 224 238,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
4,Postal Address,P.O Box 80424,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
5,Email,kabwemunicipalcouncil@gmail.com,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
6,Official Website,https://www.kabwecouncil.gov.zm,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275

In [29]:
output_file = "data/processed/administrative_information/db-unza26-csc4792-administrative-information.csv"

council_info_df.to_csv(
    output_file,
    sep="|",
    index=False,
    encoding="utf-8"
)

print("Final administrative CSV saved:")
print(output_file)

Final administrative CSV saved:
data/processed/administrative_information/db-unza26-csc4792-administrative-information.csv

In [30]:
final_df = pd.read_csv(
    output_file,
    sep="|",
    encoding="utf-8"
)

print("Rows:", len(final_df))
print("Columns:", len(final_df.columns))
print()

print("Missing values:")
print(final_df.isnull().sum())
print()

display(final_df)

Rows: 7
Columns: 4

Missing values:
field          0
value          0
source_type    0
source_url     0
dtype: int64

,field,value,source_type,source_url
0,Council Name,Kabwe Municipal Council,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
1,Province,Central Province,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
2,Country,Zambia,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
3,Telephone,260 215 224 238,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
4,Postal Address,P.O Box 80424,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
5,Email,kabwemunicipalcouncil@gmail.com,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275
6,Official Website,https://www.kabwecouncil.gov.zm,Official webpage,https://www.kabwecouncil.gov.zm/?page_id=275

## 1.5 Administrative Leadership

Administrative leadership information was extracted from the official Kabwe
Municipal Council website.

The Office of the Town Clerk is responsible for the day-to-day operations
of the local authority. The official webpage identifies Jovax Ngoma as the
Town Clerk.

This information is stored separately from the council's contact information
but forms part of the administrative information dataset.

In [31]:
import urllib3
urllib3.disable_warnings()

town_clerk_url = "https://www.kabwecouncil.gov.zm/?page_id=2634"

town_clerk_response = requests.get(
    town_clerk_url,
    timeout=30,
    verify=False
)

print("Status code:", town_clerk_response.status_code)
print("Content type:", town_clerk_response.headers.get("Content-Type"))

Status code: 200
Content type: text/html; charset=UTF-8

In [32]:
town_clerk_soup = BeautifulSoup(
    town_clerk_response.text,
    "html.parser"
)

print(town_clerk_soup.title.get_text(strip=True))

office of the the town clerk – Kabwe Municipal Council

In [33]:
town_clerk_text = town_clerk_soup.get_text(
    separator="\n",
    strip=True
)

print(town_clerk_text[:5000])

office of the the town clerk – Kabwe Municipal Council
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Search
Institutional Management
Town Clerk
Institutional Management carries out executive functions of the council including that of His Worship of the Mayor and the Town Clerk. Units or sections that report directly to the executive head and not through another directorate are the Public Relations, Procurement, and Internal Auditing Sections
The Office of theTown Clerk
he office of the Town Clerk serving as the institution’s Chief Executive Officer CEO assumes the oversight responsibility of the day-to-day operations of the Local Authority and spearheading the delivery of developmental programs within the district.
Internal Audit Section
Procurement Section
The Internal Audit Section serves as a pivotal mechanism for maintaining operational integrity within the Local Authority. This section is responsible for developing and implementing checks, and controls, conducting risk assessments, and overseeing management procedures both at policy level and operations. Regular audits are carried out to ensure compliance with existing legislation and enhance operational efficiency. The findings from these audits are compiled into comprehensive reports, which are then presented to the executive head of the Local Authority and the Audit Committee for review and recommended action.
The Procurement Section, as a critical component of the institution, is responsible for overseeing and managing all procurement processes. This section ensures that all purchases of goods and services are conducted per established policies, legislation, and procedures promoting transparency, fairness, and cost-effectiveness. Regular compliance controls are performed to verify adherence to procurement guidelines and to identify areas for improvement. The Procurement Section plays a vital role in supporting the institution’s operations and strategic objectives and in the delivery of the CDF project procurement and delivery.
The Public Procurement Act No. 8 of 2020
Public Procurement Regulations 2022
Public Relations Section
Information Communications Technology Unit
The Public Relations Unit is crucial in managing and disseminating information to the citizens. The unit is responsible for the strategic communication processes that build mutually beneficial relationships with the public as the face and the mouthpiece of the Local Authority.
The Public Relations Unit handles various public functions and events for the LA including anticipating, analyzing, and interpreting public opinion, perceptions, and attitudes toward the council. It drafts strategies that use free or paid media, print or electronic to counteract information gaps and conduct sensitizations on council and developmental projects and operations.
Responsible for drafting and distributing press releases, planning and executing special public outreach and media relations events, and developing a crisis public relations strategy. It also handles the council’s social media presence and responds to public reviews on social media websites.
In essence, the Public Relations Unit is instrumental in maintaining a positive reputation of the council and fostering a strategic relationship with the public, prospective partners, investors, employees, and other stakeholders.
The section is responsible for providing support services to the operations of the Local Authority in the area of ICT services to enhance service delivery and optimize operations. Some of the key responsibilities are:
Design and Administration of Computerized Systems.
Provide Training to staff.
Research and Development.
Contact Information
Kabwe Municipal Council
Central Province, Zambia
T

In [34]:
administrative_leadership = [
    [
        "Town Clerk",
        "Jovax Ngoma",
        "Administrative leadership",
        town_clerk_url
    ]
]

leadership_df = pd.DataFrame(
    administrative_leadership,
    columns=[
        "field",
        "value",
        "category",
        "source_url"
    ]
)

display(leadership_df)

,field,value,category,source_url
0,Town Clerk,Jovax Ngoma,Administrative leadership,https://www.kabwecouncil.gov.zm/?page_id=2634

## 1.6 Council Departments

The official Kabwe Municipal Council Departments webpage was used to
identify the council's administrative departments.

The department names are preserved as published by the council. No
department names are invented or renamed during extraction.

In [35]:
import urllib3
urllib3.disable_warnings()

departments_url = "https://www.kabwecouncil.gov.zm/?page_id=770"

departments_response = requests.get(
    departments_url,
    timeout=30,
    verify=False
)

print("Status code:", departments_response.status_code)
print("Content type:", departments_response.headers.get("Content-Type"))

Status code: 200
Content type: text/html; charset=UTF-8

In [36]:
departments_soup = BeautifulSoup(
    departments_response.text,
    "html.parser"
)

print(departments_soup.title.get_text(strip=True))

Departments – Kabwe Municipal Council

In [37]:
departments_text = departments_soup.get_text(
    separator="\n",
    strip=True
)

print(departments_text[:8000])

Departments – Kabwe Municipal Council
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Menu
Home
About
Open menu
About Us
Mandate
Who we are
Departments
office of the the town clerk
Dept of Human Resource and Administration
Dept of Health
Dept of Finance
Dept of Engineering Services
Dept of Health Services
Dept Legal ( Services Unit)
Dept Of Planning
Dept Of Housing and Social Services
Dept of Fisheries, Livestock And Veterinary Services
Dept of Agriculture
Civic Leaders
The Mayor
Kabwe Central
Bwacha
Services
Open menu
Licenses and levies
Waste Management
E-GP
News Updates
CDF
Open menu
CDF GUIDLINES
CDF branding guidelines
ZDSP
Media
Open menu
Publications
Public Notices
Photo Gallery
video gallery
Forms
ADD A VIDEO
Contact Us
FAQS
Search
Institutional Management
Development Planning
Legal Services
Engineering  Services
Finance
Housing and Social Services
Human Resource & Administration
Public Health
Institutional Management
Consists of the principal officer who in this regard is the Town Clerk, as well as Public Relations, Procurement and Audit sections.
Development Planning
The department is responsible for coordinating spartial planning, social economic development and evironmental management in the district.
Legal Services
It deals with legal matters and is responsible in ensuring that legal issues and interest of the council are taken care of.
It provides legal consultation, advice and also reveals the laws, rules, contracts and agreements granted by other departments in the council.  The department also offers the services of commissioning documents.
Engineering  Services
The role of this department is to facilitate engineering services such as; feeder roads, borehole drilling, inspection of buildings, scrutinizing building plans to make sure it is the required standard, fire brigade services, maintenance of plant and machinery.
Finance
The department administrates all finance related services as well as Information Technology and valuation section.
Housing and Social Services
The department is responsible for planning and implementation of various social services, management of Social Amenities and recreation facilities run by the council.  The department of Housing and Social Services is made of six (6) sections as follows:
Settlement
Library
Community Development
Housing
Bus Stations
Markets
Human Resource & Administration
The department is responsible for the administrative processes that ensure good governance and the achievement of Council’s strategic objectives.  The department incorporates the Section of Administration, Committee Services, Human Resources, Records Management and Public Participation.
Public Health
The department focuses on preventing diseases, prolonging life and improving the quality of life for individuals and communities through environmental health services.
Contact Information
Kabwe Municipal Council
Central Province, Zambia
Tel: 260 215 224 238
P.O Box: 80424
Email: kabwemunicipalcouncil@gmail.com
Complaint
Follow Us
Quick Links
Ministry of Local Government and Rural Development
Local Government Service Comission
Ministry of Finance and National Planning
Ministry of Agriculture
National Assembly of Zambia
Local Government Training Institute
SMART Zambia
©2023. SMART Zambia Institute. All Rights Reserved.

In [38]:
departments = [
    ["Institutional Management", "Council Department", departments_url],
    ["Development Planning", "Council Department", departments_url],
    ["Legal Services", "Council Department", departments_url],
    ["Engineering Services", "Council Department", departments_url],
    ["Finance", "Council Department", departments_url],
    ["Housing and Social Services", "Council Department", departments_url],
    ["Human Resource & Administration", "Council Department", departments_url],
    ["Public Health", "Council Department", departments_url]
]

departments_df = pd.DataFrame(
    departments,
    columns=[
        "field",
        "value",
        "category"
    ]
)

departments_df["source_url"] = departments_df["category"].apply(
    lambda x: departments_url
)

departments_df["category"] = "Council Department"

display(departments_df)

,field,value,category,source_url
0,Institutional Management,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
1,Development Planning,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
2,Legal Services,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
3,Engineering Services,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
4,Finance,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
5,Housing and Social Services,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
6,Human Resource & Administration,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
7,Public Health,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770

In [39]:
print("Number of departments:", len(departments_df))

Number of departments: 8

In [40]:
# Standardise the basic council information structure.

council_admin_df = council_info_df.copy()

council_admin_df["category"] = "Council Information"

council_admin_df = council_admin_df[
    [
        "field",
        "value",
        "category",
        "source_url"
    ]
]

display(council_admin_df)

,field,value,category,source_url
0,Council Name,Kabwe Municipal Council,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
1,Province,Central Province,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
2,Country,Zambia,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
3,Telephone,260 215 224 238,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
4,Postal Address,P.O Box 80424,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
5,Email,kabwemunicipalcouncil@gmail.com,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
6,Official Website,https://www.kabwecouncil.gov.zm,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275

In [41]:
administrative_information_df = pd.concat(
    [
        council_admin_df,
        leadership_df,
        departments_df
    ],
    ignore_index=True
)

display(administrative_information_df)

,field,value,category,source_url
0,Council Name,Kabwe Municipal Council,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
1,Province,Central Province,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
2,Country,Zambia,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
3,Telephone,260 215 224 238,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
4,Postal Address,P.O Box 80424,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
5,Email,kabwemunicipalcouncil@gmail.com,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
6,Official Website,https://www.kabwecouncil.gov.zm,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
7,Town Clerk,Jovax Ngoma,Administrative leadership,https://www.kabwecouncil.gov.zm/?page_id=2634
8,Institutional Management,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
9,Development Planning,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
10,Legal Services,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
11,Engineering Services,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
12,Finance,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
13,Housing and Social Services,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
14,Human Resource & Administration,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
15,Public Health,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770

In [42]:
print("Total records:", len(administrative_information_df))
print("Total columns:", len(administrative_information_df.columns))
print()

print("Missing values:")
print(administrative_information_df.isnull().sum())
print()

print("Duplicate records:")
print(
    administrative_information_df.duplicated().sum()
)

Total records: 16
Total columns: 4

Missing values:
field         0
value         0
category      0
source_url    0
dtype: int64

Duplicate records:
0

In [43]:
final_output_file = (
    "data/processed/administrative_information/db-unza26-csc4792-administrative-information.csv"
)

administrative_information_df.to_csv(
    final_output_file,
    sep="|",
    index=False,
    encoding="utf-8"
)

print("Final CSV saved:")
print(final_output_file)

Final CSV saved:
data/processed/administrative_information/db-unza26-csc4792-administrative-information.csv

In [44]:
final_admin_df = pd.read_csv(
    final_output_file,
    sep="|",
    encoding="utf-8"
)

print("Rows:", len(final_admin_df))
print("Columns:", len(final_admin_df.columns))

display(final_admin_df)

Rows: 16
Columns: 4

,field,value,category,source_url
0,Council Name,Kabwe Municipal Council,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
1,Province,Central Province,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
2,Country,Zambia,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
3,Telephone,260 215 224 238,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
4,Postal Address,P.O Box 80424,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
5,Email,kabwemunicipalcouncil@gmail.com,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
6,Official Website,https://www.kabwecouncil.gov.zm,Council Information,https://www.kabwecouncil.gov.zm/?page_id=275
7,Town Clerk,Jovax Ngoma,Administrative leadership,https://www.kabwecouncil.gov.zm/?page_id=2634
8,Institutional Management,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
9,Development Planning,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
10,Legal Services,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
11,Engineering Services,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
12,Finance,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
13,Housing and Social Services,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
14,Human Resource & Administration,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770
15,Public Health,Council Department,Council Department,https://www.kabwecouncil.gov.zm/?page_id=770

In [45]:
print("===== FINAL VALIDATION =====")

print("File:", final_output_file)
print("Rows:", len(final_admin_df))
print("Columns:", len(final_admin_df.columns))

print("\nMissing values:")
print(final_admin_df.isnull().sum())

print("\nDuplicate rows:")
print(final_admin_df.duplicated().sum())

print("\nCategories:")
print(final_admin_df["category"].value_counts())

print("\nSeparator: |")

===== FINAL VALIDATION =====
File: data/processed/administrative_information/db-unza26-csc4792-administrative-information.csv
Rows: 16
Columns: 4

Missing values:
field         0
value         0
category      0
source_url    0
dtype: int64

Duplicate rows:
0

Categories:
category
Council Department           8
Council Information          7
Administrative leadership    1
Name: count, dtype: int64

Separator: |